//! The package graph (`package_graph::resolve_packages`) through the
//! binary: what a lockfile may and may not decide, relative git URLs, a
//! git `rev` that is a commit prefix, and symbolic links in a
//! dependency. The golden cases under `tests/golden/cli/packages/stage5_pkg__*`
//! cover what needs no lockfile and no repository.
//!
//! Hermeticity: every `silt` invocation gets a git checkout cache inside
//! its own workspace (`XDG_CACHE_HOME`, `LOCALAPPDATA`) and an empty git
//! configuration. Nothing uses the network: the repositories are local
//! directories built by the test. Tests that build one are skipped when
//! `git` is not installed.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicUsize, Ordering};

use silt::intern;
use silt::package_graph::{LockPolicy, resolve_packages};
use silt::source::SourceMap;

static COUNTER: AtomicUsize = AtomicUsize::new(0);

fn fresh_workspace(tag: &str) -> PathBuf {
    let n = COUNTER.fetch_add(1, Ordering::SeqCst);
    let dir =
        std::env::temp_dir().join(format!("silt_stage5_pkg_{tag}_{}_{n}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    fs::write(dir.join("gitconfig"), "").unwrap();
    dir
}

fn isolate_git(cmd: &mut Command, ws: &Path) {
    cmd.env("GIT_CONFIG_NOSYSTEM", "1")
        .env("GIT_CONFIG_GLOBAL", ws.join("gitconfig"))
        .env("GIT_TERMINAL_PROMPT", "0");
    for var in ["GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE"] {
        cmd.env_remove(var);
    }
}

/// Run `silt <args>` in `cwd` with the checkout cache in `ws`.
fn silt(ws: &Path, cwd: &Path, args: &[&str]) -> Output {
    let mut cmd = Command::new(env!("CARGO_BIN_EXE_silt"));
    cmd.args(args)
        .current_dir(cwd)
        .env("XDG_CACHE_HOME", ws.join("cache"))
        .env("LOCALAPPDATA", ws.join("cache"))
        .env("NO_COLOR", "1");
    isolate_git(&mut cmd, ws);
    cmd.output().expect("failed to spawn silt binary")
}

fn stdout(out: &Output) -> String {
    String::from_utf8_lossy(&out.stdout).into_owned()
}

fn stderr(out: &Output) -> String {
    String::from_utf8_lossy(&out.stderr).into_owned()
}

/// A package at `dir`: `silt.toml` with `name` and the `[dependencies]`
/// lines `deps`, and `src/<file>` holding `body`.
fn write_package(dir: &Path, name: &str, deps: &[&str], file: &str, body: &str) {
    fs::create_dir_all(dir.join("src")).unwrap();
    let mut manifest = format!("[package]\nname = \"{name}\"\nversion = \"0.1.0\"\n");
    if !deps.is_empty() {
        manifest.push_str("\n[dependencies]\n");
        for dep in deps {
            manifest.push_str(dep);
            manifest.push('\n');
        }
    }
    fs::write(dir.join("silt.toml"), manifest).unwrap();
    fs::write(dir.join("src").join(file), body).unwrap();
}

fn git_installed() -> bool {
    let ok = Command::new("git")
        .arg("--version")
        .output()
        .map(|out| out.status.success())
        .unwrap_or(false);
    if !ok {
        eprintln!("SKIP: `git` is not installed");
    }
    ok
}

/// Run `git <args>` in `cwd` with a fixed identity; trimmed stdout.
fn git(ws: &Path, cwd: &Path, args: &[&str]) -> String {
    let mut cmd = Command::new("git");
    cmd.args(["-c", "user.name=silt tests"])
        .args(["-c", "user.email=tests@silt.local"])
        .args(["-c", "commit.gpgsign=false"])
        .args(args)
        .current_dir(cwd);
    isolate_git(&mut cmd, ws);
    let out = cmd.output().expect("spawn git");
    assert!(
        out.status.success(),
        "git {args:?} failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8_lossy(&out.stdout).trim().to_string()
}

/// Make `repo` a repository on the branch `main` and commit everything
/// in it; returns the commit id.
fn commit_all(ws: &Path, repo: &Path, message: &str) -> String {
    if !repo.join(".git").exists() {
        git(ws, repo, &["init", "--quiet"]);
        git(ws, repo, &["symbolic-ref", "HEAD", "refs/heads/main"]);
    }
    git(ws, repo, &["add", "-A"]);
    git(ws, repo, &["commit", "--quiet", "-m", message]);
    git(ws, repo, &["rev-parse", "HEAD"])
}

/// The canonical form of `path` as silt writes it into silt.lock: a
/// TOML string, without the `\\?\` prefix Windows gives a canonical
/// path.
fn toml_path(path: &Path) -> String {
    let canonical = fs::canonicalize(path).unwrap().display().to_string();
    let plain = canonical.strip_prefix(r"\\?\").unwrap_or(&canonical);
    format!("\"{}\"", plain.replace('\\', "\\\\"))
}

const LOCK_HEADER: &str = "# This file is generated by silt. Do not edit by hand.\nversion = 1\n";

/// An app whose manifest gives `x = { path = "good" }`, with packages
/// named `x` at `good/` and `evil/`, and a lockfile that pins `x` to
/// `evil`.
fn app_with_a_lock_pinning_another_source(ws: &Path) -> PathBuf {
    let app = ws.join("app");
    write_package(
        &app,
        "app",
        &["x = { path = \"good\" }"],
        "main.silt",
        "import x\nfn main() { println(x.which()) }\n",
    );
    for which in ["good", "evil"] {
        write_package(
            &app.join(which),
            "x",
            &[],
            "lib.silt",
            &format!("pub fn which() {{ \"{which}\" }}\n"),
        );
    }
    fs::write(
        app.join("silt.lock"),
        format!(
            "{LOCK_HEADER}\n[[package]]\nname = \"app\"\nversion = \"0.1.0\"\n\n\
             [[package]]\nname = \"x\"\nversion = \"0.1.0\"\n\
             source = {{ path = {} }}\nchecksum = \"sha256:0\"\n",
            toml_path(&app.join("evil"))
        ),
    )
    .unwrap();
    app
}

// ── The lockfile never overrides the manifest ─────────────────────────

/// FAILS on the base: only the names in the lock were compared with the
/// manifest, so the lock's `evil` was loaded.
#[test]
fn a_lock_entry_for_another_source_is_stale_and_rewritten() {
    let ws = fresh_workspace("lock_override");
    let app = app_with_a_lock_pinning_another_source(&ws);

    let out = silt(&ws, &app, &["run"]);

    assert!(out.status.success(), "{}", stderr(&out));
    assert_eq!(stdout(&out), "good\n", "stderr: {}", stderr(&out));
    assert!(
        stderr(&out).contains("Updating silt.lock"),
        "{}",
        stderr(&out)
    );
    let lock = fs::read_to_string(app.join("silt.lock")).unwrap();
    assert!(
        lock.contains(&format!("path = {}", toml_path(&app.join("good")))),
        "the rewritten lock pins the manifest's source:\n{lock}"
    );
    let _ = fs::remove_dir_all(&ws);
}

/// `disasm` never writes the lock: a stale entry is an error at the
/// dependency in silt.toml. FAILS on the base: `evil` was disassembled.
#[test]
fn a_stale_lock_entry_is_an_error_when_the_lock_is_read_only() {
    let ws = fresh_workspace("lock_readonly");
    let app = app_with_a_lock_pinning_another_source(&ws);
    let before = fs::read_to_string(app.join("silt.lock")).unwrap();

    let out = silt(&ws, &app, &["disasm"]);

    let err = stderr(&out);
    assert_eq!(out.status.code(), Some(1), "{err}");
    assert!(
        err.starts_with(
            "error[package]: silt.lock is out of date for dependency `x`: \
             it pins another source than this one"
        ) && err.contains(" --> silt.toml:6:5")
            && err.contains("help: run `silt update`"),
        "{err}"
    );
    assert_eq!(fs::read_to_string(app.join("silt.lock")).unwrap(), before);
    let _ = fs::remove_dir_all(&ws);
}

/// FAILS on the base: a bare `error: invalid lockfile ...` line.
#[test]
fn an_invalid_lockfile_is_a_diagnostic_in_it() {
    let ws = fresh_workspace("lock_invalid");
    let app = ws.join("app");
    write_package(&app, "app", &[], "main.silt", "fn main() {}\n");
    fs::write(
        app.join("silt.lock"),
        format!("{LOCK_HEADER}\n[[package]]\nname = \"app\"\n"),
    )
    .unwrap();

    let out = silt(&ws, &app, &["check"]);

    let err = stderr(&out);
    assert_eq!(out.status.code(), Some(1), "{err}");
    assert!(
        err.starts_with("error[package]: invalid lockfile: [[package]] `app` missing `version`")
            && err.contains(" --> silt.lock:4:1"),
        "{err}"
    );
    let _ = fs::remove_dir_all(&ws);
}

/// A commit prefix in the lock is no pin: it could name a tag. FAILS on
/// the base, which took any 7 to 64 hexadecimal characters.
#[test]
fn a_lock_rev_must_be_a_full_commit_id() {
    let ws = fresh_workspace("lock_short_rev");
    let app = ws.join("app");
    write_package(
        &app,
        "app",
        &["remote = { git = \"./nowhere\", branch = \"main\" }"],
        "main.silt",
        "fn main() {}\n",
    );
    fs::write(
        app.join("silt.lock"),
        format!(
            "{LOCK_HEADER}\n[[package]]\nname = \"app\"\nversion = \"0.1.0\"\n\n\
             [[package]]\nname = \"remote\"\nversion = \"0.1.0\"\n\
             source = {{ git = \"./nowhere\", branch = \"main\", rev = \"abc1234\" }}\n\
             checksum = \"sha256:0\"\n"
        ),
    )
    .unwrap();

    let out = silt(&ws, &app, &["check"]);

    let err = stderr(&out);
    assert_eq!(out.status.code(), Some(1), "{err}");
    assert!(
        err.contains("invalid `rev` `abc1234`: expected a full commit id")
            && err.contains(" --> silt.lock:11:54"),
        "{err}"
    );
    let _ = fs::remove_dir_all(&ws);
}

// ── Relative git URLs ─────────────────────────────────────────────────

/// A repository `lib` beside the app, holding the package `remote`.
fn sibling_repository(ws: &Path, body: &str) -> String {
    let repo = ws.join("lib");
    write_package(&repo, "remote", &[], "lib.silt", body);
    commit_all(ws, &repo, "one")
}

/// `git = "../lib"` is relative to silt.toml, wherever silt runs. FAILS
/// on the base: git resolved it against the working directory,
/// `app/src`, where there is no `../lib`.
#[test]
fn a_relative_git_url_resolves_against_the_manifest_from_another_directory() {
    let ws = fresh_workspace("rel_git_cwd");
    if !git_installed() {
        return;
    }
    let head = sibling_repository(&ws, "pub fn v() { \"from lib\" }\n");
    let app = ws.join("app");
    write_package(
        &app,
        "app",
        &["remote = { git = \"../lib\", branch = \"main\" }"],
        "main.silt",
        "import remote\nfn main() { println(remote.v()) }\n",
    );

    let out = silt(&ws, &app.join("src"), &["run"]);

    assert!(out.status.success(), "{}", stderr(&out));
    assert_eq!(stdout(&out), "from lib\n");
    let lock = fs::read_to_string(app.join("silt.lock")).unwrap();
    assert!(
        lock.contains(&format!("git = {}", toml_path(&ws.join("lib"))))
            && lock.contains(&format!("rev = \"{head}\"")),
        "the lock records the URL made absolute and the commit:\n{lock}"
    );
    let _ = fs::remove_dir_all(&ws);
}

/// GUARD (passes on the base too): a relative `path` is relative to
/// silt.toml, wherever silt runs.
#[test]
fn a_relative_path_dependency_resolves_against_the_manifest_from_another_directory() {
    let ws = fresh_workspace("rel_path_cwd");
    let app = ws.join("app");
    write_package(
        &app,
        "app",
        &["calc = { path = \"../calc\" }"],
        "main.silt",
        "import calc\nfn main() { println(calc.two()) }\n",
    );
    write_package(
        &ws.join("calc"),
        "calc",
        &[],
        "lib.silt",
        "pub fn two() { 2 }\n",
    );

    let out = silt(&ws, &app.join("src"), &["run"]);

    assert!(out.status.success(), "{}", stderr(&out));
    assert_eq!(stdout(&out), "2\n");
    let _ = fs::remove_dir_all(&ws);
}

/// `silt add --git` takes a relative path from the working directory and
/// stores it relative to silt.toml. FAILS on the base: stored verbatim.
#[test]
fn silt_add_stores_a_relative_git_url_relative_to_the_manifest() {
    let ws = fresh_workspace("rel_git_add");
    if !git_installed() {
        return;
    }
    sibling_repository(&ws, "pub fn v() { 1 }\n");
    let app = ws.join("app");
    write_package(&app, "app", &[], "main.silt", "fn main() {}\n");

    let out = silt(
        &ws,
        &app.join("src"),
        &["add", "remote", "--git", "../../lib", "--branch", "main"],
    );

    assert!(out.status.success(), "{}", stderr(&out));
    let manifest = fs::read_to_string(app.join("silt.toml")).unwrap();
    assert!(
        manifest.contains("remote = { git = \"../lib\", branch = \"main\" }"),
        "{manifest}"
    );
    // And it resolves from the package root too.
    let check = silt(&ws, &app, &["check"]);
    assert!(check.status.success(), "{}", stderr(&check));
    let _ = fs::remove_dir_all(&ws);
}

// ── A rev that is a commit prefix ─────────────────────────────────────

/// A repository with two commits and a tag named like the first commit's
/// 7-character prefix, pointing at the second. The manifest's `rev` is
/// that prefix: it names the first commit, never the tag. FAILS on the
/// base: `git checkout <prefix>` took the tag, and the lock pinned the
/// prefix.
#[test]
fn a_short_rev_is_the_commit_it_starts_never_a_tag_of_that_name() {
    let ws = fresh_workspace("short_rev");
    if !git_installed() {
        return;
    }
    let repo = ws.join("lib");
    write_package(&repo, "remote", &[], "lib.silt", "pub fn v() { \"one\" }\n");
    let first = commit_all(&ws, &repo, "one");
    fs::write(repo.join("src/lib.silt"), "pub fn v() { \"two\" }\n").unwrap();
    let second = commit_all(&ws, &repo, "two");
    let prefix = &first[..7];
    git(&ws, &repo, &["tag", prefix, &second]);

    let app = ws.join("app");
    let dep = format!("remote = {{ git = \"../lib\", rev = \"{prefix}\" }}");
    write_package(
        &app,
        "app",
        &[&dep],
        "main.silt",
        "import remote\nfn main() { println(remote.v()) }\n",
    );

    let out = silt(&ws, &app, &["run"]);

    assert!(out.status.success(), "{}", stderr(&out));
    assert_eq!(stdout(&out), "one\n", "the prefix names the first commit");
    let lock = fs::read_to_string(app.join("silt.lock")).unwrap();
    assert!(
        lock.contains(&format!("rev = \"{first}\"")),
        "the lock stores the full commit id:\n{lock}"
    );
    // The second run reuses the pin.
    let again = silt(&ws, &app, &["run"]);
    assert_eq!(stdout(&again), "one\n", "{}", stderr(&again));
    assert!(!stderr(&again).contains("Updating"), "{}", stderr(&again));
    let _ = fs::remove_dir_all(&ws);
}

// ── Symbolic links ────────────────────────────────────────────────────

/// FAILS on the base: the link was followed and its target loaded.
#[cfg(unix)]
#[test]
fn a_symlink_in_a_path_dependency_is_rejected() {
    let ws = fresh_workspace("symlink_path");
    let app = ws.join("app");
    write_package(
        &app,
        "app",
        &["dep = { path = \"../dep\" }"],
        "main.silt",
        "import dep\nfn main() { println(dep.f()) }\n",
    );
    let dep = ws.join("dep");
    fs::create_dir_all(dep.join("src")).unwrap();
    fs::write(
        dep.join("silt.toml"),
        "[package]\nname = \"dep\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    fs::write(ws.join("elsewhere.silt"), "pub fn f() { \"elsewhere\" }\n").unwrap();
    std::os::unix::fs::symlink(ws.join("elsewhere.silt"), dep.join("src/lib.silt")).unwrap();

    let out = silt(&ws, &app, &["run"]);

    let err = stderr(&out);
    assert_eq!(out.status.code(), Some(1), "{err}");
    assert!(stdout(&out).is_empty(), "nothing runs: {}", stdout(&out));
    assert!(
        err.starts_with(
            "error[package]: dependency `dep` contains a symbolic link: `src/lib.silt`"
        ) && err.contains(" --> silt.toml:6:7"),
        "{err}"
    );
    let _ = fs::remove_dir_all(&ws);
}

/// A repository that holds a symbolic link is not checked out into the
/// cache. FAILS on the base: the clone was cached and the link followed.
#[cfg(unix)]
#[test]
fn a_symlink_in_a_git_dependency_is_rejected() {
    let ws = fresh_workspace("symlink_git");
    if !git_installed() {
        return;
    }
    let repo = ws.join("lib");
    fs::create_dir_all(repo.join("src")).unwrap();
    fs::write(
        repo.join("silt.toml"),
        "[package]\nname = \"remote\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    std::os::unix::fs::symlink("/etc/hostname", repo.join("src/lib.silt")).unwrap();
    commit_all(&ws, &repo, "a link");

    let app = ws.join("app");
    write_package(
        &app,
        "app",
        &["remote = { git = \"../lib\", branch = \"main\" }"],
        "main.silt",
        "import remote\nfn main() {}\n",
    );

    let out = silt(&ws, &app, &["check"]);

    let err = stderr(&out);
    assert_eq!(out.status.code(), Some(1), "{err}");
    assert!(
        err.starts_with(
            "error[package]: dependency `remote` contains a symbolic link: `src/lib.silt`"
        ) && err.contains(" --> silt.toml:6:10"),
        "{err}"
    );
    // Nothing was left in the cache for it.
    let cached: Vec<PathBuf> = fs::read_dir(ws.join("cache/silt/git"))
        .map(|dirs| {
            dirs.flatten()
                .flat_map(|d| fs::read_dir(d.path()).into_iter().flatten().flatten())
                .map(|e| e.path())
                .collect()
        })
        .unwrap_or_default();
    assert!(
        cached.is_empty(),
        "the checkout must not be cached: {cached:?}"
    );
    let _ = fs::remove_dir_all(&ws);
}

// ── Identity by source ────────────────────────────────────────────────

/// Two keys naming one directory give one package, known by both keys.
#[test]
fn two_keys_for_one_source_are_one_package() {
    let ws = fresh_workspace("two_keys");
    let app = ws.join("app");
    write_package(
        &app,
        "app",
        &[
            "a = { path = \"../shared\" }",
            "b = { path = \"../x/../shared\" }",
        ],
        "main.silt",
        "fn main() {}\n",
    );
    write_package(
        &ws.join("shared"),
        "shared",
        &[],
        "lib.silt",
        "pub fn f() { 1 }\n",
    );

    let graph = resolve_packages(&app, LockPolicy::ReadOnly, &mut SourceMap::new())
        .unwrap_or_else(|d| panic!("{d:?}"));

    assert_eq!(graph.packages.len(), 2, "{graph:?}");
    let a = graph.dependency(graph.root, intern::intern("a"));
    let b = graph.dependency(graph.root, intern::intern("b"));
    assert!(a.is_some() && a == b, "{graph:?}");
    let shared = graph.package(a.unwrap());
    assert_eq!(intern::resolve(shared.name), "shared");
    assert!(
        shared.src.ends_with(Path::new("shared").join("src")),
        "{shared:?}"
    );
    let _ = fs::remove_dir_all(&ws);
}

// ── Fix round: lock pins, the symlink rule, the cache race, silt add ──

/// A read-only lock without an entry for the dependency says so, rather
/// than that it pins another source.
#[test]
fn a_read_only_lock_without_the_dependency_has_no_pin() {
    let ws = fresh_workspace("lock_no_pin");
    let app = app_with_a_lock_pinning_another_source(&ws);
    fs::write(
        app.join("silt.lock"),
        format!("{LOCK_HEADER}\n[[package]]\nname = \"app\"\nversion = \"0.1.0\"\n"),
    )
    .unwrap();

    let out = silt(&ws, &app, &["disasm"]);

    let err = stderr(&out);
    assert_eq!(out.status.code(), Some(1), "{err}");
    assert!(
        err.starts_with(
            "error[package]: silt.lock is out of date for dependency `x`: \
             it has no pin for this source"
        ),
        "{err}"
    );
    let _ = fs::remove_dir_all(&ws);
}

/// The symlink rule covers `silt.toml` as well as `src/`.
#[cfg(unix)]
#[test]
fn a_symlinked_manifest_in_a_path_dependency_is_rejected() {
    let ws = fresh_workspace("symlink_manifest");
    let app = ws.join("app");
    write_package(
        &app,
        "app",
        &["dep = { path = \"../dep\" }"],
        "main.silt",
        "fn main() {}\n",
    );
    let dep = ws.join("dep");
    fs::create_dir_all(dep.join("src")).unwrap();
    fs::write(dep.join("src/lib.silt"), "pub fn f() { 1 }\n").unwrap();
    fs::write(
        ws.join("elsewhere.toml"),
        "[package]\nname = \"dep\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    std::os::unix::fs::symlink(ws.join("elsewhere.toml"), dep.join("silt.toml")).unwrap();

    let out = silt(&ws, &app, &["check"]);

    let err = stderr(&out);
    assert_eq!(out.status.code(), Some(1), "{err}");
    assert!(
        err.starts_with("error[package]: dependency `dep` contains a symbolic link: `silt.toml`"),
        "{err}"
    );
    let _ = fs::remove_dir_all(&ws);
}

/// A dependency root reached through a symbolic link is allowed, and so
/// is a link outside `silt.toml` and `src/`, which silt never reads.
#[cfg(unix)]
#[test]
fn a_path_dependency_reached_through_a_link_is_allowed() {
    let ws = fresh_workspace("symlink_root");
    let app = ws.join("app");
    write_package(
        &app,
        "app",
        &["dep = { path = \"../dep_link\" }"],
        "main.silt",
        "import dep\nfn main() { println(dep.f()) }\n",
    );
    let real = ws.join("real_dep");
    write_package(&real, "dep", &[], "lib.silt", "pub fn f() { \"real\" }\n");
    std::os::unix::fs::symlink("/etc/hostname", real.join("README")).unwrap();
    std::os::unix::fs::symlink(&real, ws.join("dep_link")).unwrap();

    let out = silt(&ws, &app, &["run"]);

    assert!(out.status.success(), "{}", stderr(&out));
    assert_eq!(stdout(&out), "real\n");
    let _ = fs::remove_dir_all(&ws);
}

/// The same rule for a git dependency: a link outside `silt.toml` and
/// `src/` does not stop the checkout from being cached and used.
#[cfg(unix)]
#[test]
fn a_symlink_outside_the_sources_of_a_git_dependency_is_allowed() {
    let ws = fresh_workspace("symlink_git_outside");
    if !git_installed() {
        return;
    }
    let repo = ws.join("lib");
    write_package(
        &repo,
        "remote",
        &[],
        "lib.silt",
        "pub fn v() { \"linked docs\" }\n",
    );
    std::os::unix::fs::symlink("/etc/hostname", repo.join("README")).unwrap();
    commit_all(&ws, &repo, "a link outside src");
    let app = ws.join("app");
    write_package(
        &app,
        "app",
        &["remote = { git = \"../lib\", branch = \"main\" }"],
        "main.silt",
        "import remote\nfn main() { println(remote.v()) }\n",
    );

    let out = silt(&ws, &app, &["run"]);

    assert!(out.status.success(), "{}", stderr(&out));
    assert_eq!(stdout(&out), "linked docs\n");
    let _ = fs::remove_dir_all(&ws);
}

/// Four processes fetching one commit into a cold cache at once all
/// succeed, and leave one checkout and no temporary directory. FAILED
/// before the fix most of the time: they shared one `<rev>.tmp`.
#[test]
fn concurrent_cold_cache_fetches_all_succeed() {
    let ws = fresh_workspace("cache_race");
    if !git_installed() {
        return;
    }
    let head = sibling_repository(&ws, "pub fn v() { 7 }\n");
    let mut apps = Vec::new();
    for i in 0..4 {
        let app = ws.join(format!("app{i}"));
        let dep = format!("remote = {{ git = \"../lib\", rev = \"{head}\" }}");
        write_package(
            &app,
            "app",
            &[&dep],
            "main.silt",
            "import remote\nfn main() {}\n",
        );
        apps.push(app);
    }

    let outs: Vec<Output> = std::thread::scope(|scope| {
        let handles: Vec<_> = apps
            .iter()
            .map(|app| scope.spawn(|| silt(&ws, app, &["check"])))
            .collect();
        handles.into_iter().map(|h| h.join().unwrap()).collect()
    });

    for out in &outs {
        assert!(out.status.success(), "{}", stderr(out));
    }
    let url_dirs: Vec<PathBuf> = fs::read_dir(ws.join("cache/silt/git"))
        .unwrap()
        .flatten()
        .map(|e| e.path())
        .collect();
    assert_eq!(url_dirs.len(), 1, "{url_dirs:?}");
    let entries: Vec<String> = fs::read_dir(&url_dirs[0])
        .unwrap()
        .flatten()
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .collect();
    assert_eq!(
        entries,
        [head.clone()],
        "one checkout, no temporary directory"
    );
    let _ = fs::remove_dir_all(&ws);
}

/// When the new dependency does not resolve, `silt add` leaves silt.toml
/// as it was. FAILED before the fix: the entry stayed.
#[test]
fn silt_add_leaves_the_manifest_alone_when_resolution_fails() {
    let ws = fresh_workspace("add_restore");
    let app = ws.join("app");
    write_package(&app, "app", &[], "main.silt", "fn main() {}\n");
    let before = fs::read_to_string(app.join("silt.toml")).unwrap();
    let bad = ws.join("bad");
    fs::create_dir_all(bad.join("src")).unwrap();
    fs::write(
        bad.join("silt.toml"),
        "[package]\nname = \"bad\"\nversion = \"one\"\n",
    )
    .unwrap();

    let out = silt(&ws, &app, &["add", "bad", "--path", "../bad"]);

    let err = stderr(&out);
    assert_eq!(out.status.code(), Some(1), "{err}");
    assert!(
        err.starts_with("error[package]: invalid manifest: invalid package version `one`")
            && err.contains("silt add left silt.toml as it was"),
        "{err}"
    );
    assert!(
        stdout(&out).is_empty(),
        "no success summary: {}",
        stdout(&out)
    );
    assert_eq!(fs::read_to_string(app.join("silt.toml")).unwrap(), before);
    let _ = fs::remove_dir_all(&ws);
}

/// Every package of a shared name is reported, not just the first two.
#[test]
fn three_packages_of_one_name_are_all_reported() {
    let ws = fresh_workspace("three_names");
    let app = ws.join("app");
    write_package(
        &app,
        "app",
        &[
            "a = { path = \"../x1\" }",
            "b = { path = \"../x2\" }",
            "c = { path = \"../x3\" }",
        ],
        "main.silt",
        "fn main() {}\n",
    );
    for dir in ["x1", "x2", "x3"] {
        write_package(&ws.join(dir), "x", &[], "lib.silt", "pub fn f() { 1 }\n");
    }

    let errors = resolve_packages(&app, LockPolicy::ReadOnly, &mut SourceMap::new())
        .expect_err("three sources named `x`");

    assert_eq!(errors.len(), 1, "{errors:?}");
    let d = &errors[0];
    assert_eq!(d.message, "three different packages are named `x`", "{d:?}");
    for dir in ["x1", "x2", "x3"] {
        assert!(
            d.notes.iter().any(|n| n.ends_with(dir)),
            "a note for {dir}: {d:?}"
        );
    }
    // The primary span is the third key; the other two are labels.
    assert_eq!(d.labels.len(), 2, "{d:?}");
    let _ = fs::remove_dir_all(&ws);
}
