//! The builtin modules, one `module!` each: the rows in the order of
//! the module's summary table.
//!
//! Every function row is `u(signature, summary)`: its body is the
//! module's untyped `call`. A constant is `k("name: Type", summary,
//! value)`.

use super::{Module, UntypedCall, build_module, k, module, u};
#[cfg(feature = "postgres")]
use crate::builtins::postgres;
#[cfg(feature = "tcp")]
use crate::builtins::tcp;
use crate::builtins::{
    bytes, collections, concurrency, core, crypto, encoding, http, io, json, numeric, regex,
    stream, string, time, toml, uuid,
};

#[rustfmt::skip]
pub(super) fn modules() -> Vec<Module> {
    vec![
        module! {
            name: "io",
            page: "io-fs.md",
            types: "\
                pub type IoError { IoNotFound(String), IoPermissionDenied(String), IoAlreadyExists(String), IoInvalidInput(String), IoInterrupted, IoUnexpectedEof, IoWriteZero, IoUnknown(String) }\n\
            ",
            error: "IoError",
            steps: io::call,
            rows: [
                u("fn args() -> List(String)", "Command-line arguments"),
                u("fn inspect(x: a) -> String", "Debug representation of any value"),
                u("fn read_file(path: String) -> Result(String, IoError)", "Read entire file as string"),
                u("fn read_line() -> Result(String, IoError)", "Read one line from stdin"),
                u("fn write_file(path: String, contents: String) -> Result((), IoError)", "Write string to file"),
            ],
        },
        module! {
            name: "string",
            page: "string.md",
            steps: string::call,
            rows: [
                u("fn char_code(s: String) -> Int", "Unicode code point of first character"),
                u("fn chars(s: String) -> List(String)", "Split string into single-character strings"),
                u("fn contains(s: String, sub: String) -> Bool", "Check if substring exists"),
                u("fn ends_with(s: String, suffix: String) -> Bool", "Check suffix"),
                u("fn from(x: a) -> String where a: Display", "Convert any value to its display string"),
                u("fn from_char_code(code: Int) -> String", "Character from Unicode code point"),
                u("fn index_of(s: String, needle: String) -> Option(Int)", "Character index of first occurrence"),
                u("fn byte_length(s: String) -> Int", "Length in bytes"),
                u("fn is_alnum(s: String) -> Bool", "All chars are alphanumeric"),
                u("fn is_alpha(s: String) -> Bool", "All chars are alphabetic"),
                u("fn is_digit(s: String) -> Bool", "All chars are ASCII digits"),
                u("fn is_empty(s: String) -> Bool", "String has zero length"),
                u("fn is_lower(s: String) -> Bool", "All chars are lowercase"),
                u("fn is_upper(s: String) -> Bool", "All chars are uppercase"),
                u("fn is_whitespace(s: String) -> Bool", "All chars are whitespace"),
                u("fn join(xs: List(String), sep: String) -> String", "Join list with separator"),
                u("fn last_index_of(s: String, needle: String) -> Option(Int)", "Character index of last occurrence"),
                u("fn length(s: String) -> Int", "Length in characters"),
                u("fn lines(s: String) -> List(String)", "Split on `\\n` (strips trailing `\\r`, no empty final element)"),
                u("fn pad_left(s: String, width: Int, pad: String) -> String", "Pad to width on the left"),
                u("fn pad_right(s: String, width: Int, pad: String) -> String", "Pad to width on the right"),
                u("fn repeat(s: String, n: Int) -> String", "Repeat string n times"),
                u("fn replace(s: String, from: String, to: String) -> String", "Replace all occurrences"),
                u("fn slice(s: String, start: Int, end: Int) -> String", "Substring by character indices"),
                u("fn split(s: String, separator: String) -> List(String)", "Split on separator"),
                u("fn split_at(s: String, idx: Int) -> (String, String)", "Split into two strings at character index"),
                u("fn starts_with(s: String, prefix: String) -> Bool", "Check prefix"),
                u("fn starts_with_at(s: String, offset: Int, prefix: String) -> Bool", "Check prefix at a given character offset"),
                u("fn to_lower(s: String) -> String", "Convert to lowercase"),
                u("fn to_upper(s: String) -> String", "Convert to uppercase"),
                u("fn trim(s: String) -> String", "Remove leading and trailing whitespace"),
                u("fn trim_end(s: String) -> String", "Remove trailing whitespace"),
                u("fn trim_start(s: String) -> String", "Remove leading whitespace"),
            ],
        },
        module! {
            name: "int",
            page: "int-float.md",
            types: "\
                pub type ParseError { ParseEmpty, ParseInvalidDigit(Int), ParseOverflow, ParseUnderflow }\n\
            ",
            error: "ParseError",
            call: |_vm, name, args| numeric::call_int(name, args),
            rows: [
                u("fn abs(n: Int) -> Int", "Absolute value"),
                u("fn clamp(x: Int, lo: Int, hi: Int) -> Int", "Clamp value to `[lo, hi]`"),
                u("fn max(a: Int, b: Int) -> Int", "Larger of two values"),
                u("fn min(a: Int, b: Int) -> Int", "Smaller of two values"),
                u("fn parse(s: String) -> Result(Int, ParseError)", "Parse string to integer"),
                u("fn to_float(n: Int) -> Float", "Convert to float"),
                u("fn to_string(n: Int) -> String", "Convert to string"),
            ],
        },
        module! {
            name: "float",
            page: "int-float.md",
            shares: [("int", "ParseError")],
            call: |_vm, name, args| numeric::call_float(name, args),
            rows: [
                u("fn abs(f: Float) -> Float", "Absolute value"),
                u("fn ceil(f: Float) -> Float", "Round up to nearest integer (as Float)"),
                u("fn clamp(x: Float, lo: Float, hi: Float) -> Float", "Clamp value to `[lo, hi]`"),
                u("fn floor(f: Float) -> Float", "Round down to nearest integer (as Float)"),
                u("fn max(a: Float, b: Float) -> Float", "Larger of two values"),
                u("fn min(a: Float, b: Float) -> Float", "Smaller of two values"),
                u("fn parse(s: String) -> Result(Float, ParseError)", "Parse string to float"),
                u("fn round(f: Float) -> Float", "Round to nearest integer (as Float)"),
                u("fn to_int(f: Float) -> Int", "Truncate to integer"),
                u("fn to_string(f: Float, decimals: Int) -> String", "Shortest round-trippable representation; with `decimals`, that many decimal places").optional_last(),
                k("max_value: Float", "Maximum finite value (`1.7976931348623157e+308`)", f64::MAX),
                k("min_value: Float", "Minimum finite value (`-1.7976931348623157e+308`)", f64::MIN),
                k("epsilon: Float", "Machine epsilon (`2.220446049250313e-16`)", f64::EPSILON),
                k("min_positive: Float", "Smallest positive normal (`2.2250738585072014e-308`)", f64::MIN_POSITIVE),
            ],
        },
        module! {
            name: "list",
            page: "list.md",
            types: "\
                pub type Step(a) { Stop(a), Continue(a) }\n\
            ",
            steps: collections::call_list,
            rows: [
                u("fn all(xs: List(a), f: Fn(a) -> Bool) -> Bool", "True if predicate holds for every element"),
                u("fn any(xs: List(a), f: Fn(a) -> Bool) -> Bool", "True if predicate holds for at least one element"),
                u("fn append(xs: List(a), elem: a) -> List(a)", "Add an element to the end"),
                u("fn concat(xs: List(a), ys: List(a)) -> List(a)", "Concatenate two lists"),
                u("fn contains(xs: List(a), elem: a) -> Bool where a: Equal", "Check if element is in list"),
                u("fn drop(xs: List(a), n: Int) -> List(a)", "Remove first n elements"),
                u("fn each(xs: List(a), f: Fn(a) -> ()) -> ()", "Call function for each element (side effects)"),
                u("fn enumerate(xs: List(a)) -> List((Int, a))", "Pair each element with its index"),
                u("fn filter(xs: List(a), f: Fn(a) -> Bool) -> List(a)", "Keep elements matching predicate"),
                u("fn filter_map(xs: List(a), f: Fn(a) -> Option(b)) -> List(b)", "Filter and transform in one pass"),
                u("fn find(xs: List(a), f: Fn(a) -> Bool) -> Option(a)", "First element matching predicate"),
                u("fn flat_map(xs: List(a), f: Fn(a) -> List(b)) -> List(b)", "Map then flatten"),
                u("fn flatten(xs: List(List(a))) -> List(a)", "Flatten one level of nesting"),
                u("fn fold(xs: List(a), init: b, f: Fn(b, a) -> b) -> b", "Reduce to a single value"),
                u("fn fold_until(xs: List(a), init: b, f: Fn(b, a) -> Step(b)) -> b", "Fold with early termination"),
                u("fn get(xs: List(a), i: Int) -> Option(a)", "Element at index, or None"),
                u("fn group_by(xs: List(a), f: Fn(a) -> b) -> Map(b, List(a)) where b: Hash", "Group elements by key function"),
                u("fn head(xs: List(a)) -> Option(a)", "First element, or None"),
                u("fn index_of(xs: List(a), target: a) -> Option(Int) where a: Equal", "Index of first matching element, or None"),
                u("fn intersperse(xs: List(a), sep: a) -> List(a)", "Insert separator between elements"),
                u("fn last(xs: List(a)) -> Option(a)", "Last element, or None"),
                u("fn length(xs: List(a)) -> Int", "Number of elements"),
                u("fn map(xs: List(a), f: Fn(a) -> b) -> List(b)", "Transform each element"),
                u("fn max_by(xs: List(a), key: Fn(a) -> b) -> Option(a) where b: Compare", "Element with largest key, or None"),
                u("fn min_by(xs: List(a), key: Fn(a) -> b) -> Option(a) where b: Compare", "Element with smallest key, or None"),
                u("fn prepend(xs: List(a), elem: a) -> List(a)", "Add an element to the front"),
                u("fn product(xs: List(Int)) -> Int", "Product of a list of ints (1 on empty)"),
                u("fn product_float(xs: List(Float)) -> Float", "Product of a list of floats (1.0 on empty)"),
                u("fn remove_at(xs: List(a), index: Int) -> List(a)", "Remove element at index (panics if out of range)"),
                u("fn reverse(xs: List(a)) -> List(a)", "Reverse element order"),
                u("fn scan(xs: List(a), init: b, f: Fn(b, a) -> b) -> List(b)", "Prefix fold; returns all intermediate accumulators"),
                u("fn set(xs: List(a), index: Int, value: a) -> List(a)", "Return new list with element at index replaced"),
                u("fn sort(xs: List(a)) -> List(a) where a: Compare", "Sort in natural order"),
                u("fn sort_by(xs: List(a), key: Fn(a) -> b) -> List(a) where b: Compare", "Sort by key function"),
                u("fn sum(xs: List(Int)) -> Int", "Sum a list of ints (0 on empty)"),
                u("fn sum_float(xs: List(Float)) -> Float", "Sum a list of floats (0.0 on empty)"),
                u("fn tail(xs: List(a)) -> List(a)", "All elements except the first"),
                u("fn take(xs: List(a), n: Int) -> List(a)", "Keep first n elements"),
                u("fn unfold(seed: a, f: Fn(a) -> Option((b, a))) -> List(b)", "Build a list from a seed"),
                u("fn unique(xs: List(a)) -> List(a) where a: Equal", "Remove duplicates, preserving first occurrence"),
                u("fn zip(xs: List(a), ys: List(b)) -> List((a, b))", "Pair elements from two lists"),
            ],
        },
        module! {
            name: "map",
            page: "map.md",
            steps: collections::call_map,
            rows: [
                u("fn contains(m: Map(a, b), key: a) -> Bool where a: Hash", "Check if key exists"),
                u("fn delete(m: Map(a, b), key: a) -> Map(a, b) where a: Hash", "Remove a key"),
                u("fn each(m: Map(a, b), f: Fn(a, b) -> ()) -> ()", "Iterate over all entries"),
                u("fn entries(m: Map(a, b)) -> List((a, b))", "All key-value pairs as tuples"),
                u("fn filter(m: Map(a, b), f: Fn(a, b) -> Bool) -> Map(a, b)", "Keep entries matching predicate"),
                u("fn from_entries(entries: List((a, b))) -> Map(a, b) where a: Hash", "Build map from tuple list"),
                u("fn get(m: Map(a, b), k: a) -> Option(b) where a: Hash", "Look up value by key"),
                u("fn keys(m: Map(a, b)) -> List(a)", "All keys as a list"),
                u("fn length(m: Map(a, b)) -> Int", "Number of entries"),
                u("fn map(m: Map(a, b), f: Fn(a, b) -> (c, d)) -> Map(c, d) where c: Hash", "Transform all entries"),
                u("fn merge(m1: Map(a, b), m2: Map(a, b)) -> Map(a, b) where a: Hash", "Merge two maps (right wins)"),
                u("fn set(m: Map(a, b), k: a, v: b) -> Map(a, b) where a: Hash", "Insert or update a key"),
                u("fn update(m: Map(a, b), key: a, default: b, f: Fn(b) -> b) -> Map(a, b) where a: Hash", "Update existing or insert default"),
                u("fn values(m: Map(a, b)) -> List(b)", "All values as a list"),
            ],
        },
        module! {
            name: "result",
            page: "result-option.md",
            steps: core::call_result,
            rows: [
                u("fn flat_map(r: Result(a, b), f: Fn(a) -> Result(c, b)) -> Result(c, b)", "Chain fallible operations"),
                u("fn flatten(r: Result(Result(a, b), b)) -> Result(a, b)", "Remove one nesting level"),
                u("fn is_err(r: Result(a, b)) -> Bool", "True if Err"),
                u("fn is_ok(r: Result(a, b)) -> Bool", "True if Ok"),
                u("fn map_err(r: Result(a, b), f: Fn(b) -> c) -> Result(a, c)", "Transform the error"),
                u("fn map_ok(r: Result(a, b), f: Fn(a) -> c) -> Result(c, b)", "Transform the success value"),
                u("fn unwrap_or(r: Result(a, b), default: a) -> a", "Extract value or use default"),
            ],
        },
        module! {
            name: "option",
            page: "result-option.md",
            steps: core::call_option,
            rows: [
                u("fn flat_map(opt: Option(a), f: Fn(a) -> Option(b)) -> Option(b)", "Chain optional operations"),
                u("fn is_none(opt: Option(a)) -> Bool", "True if None"),
                u("fn is_some(opt: Option(a)) -> Bool", "True if Some"),
                u("fn map(opt: Option(a), f: Fn(a) -> b) -> Option(b)", "Transform the inner value"),
                u("fn to_result(opt: Option(a), error: b) -> Result(a, b)", "Convert to Result with error value"),
                u("fn unwrap_or(opt: Option(a), default: a) -> a", "Extract value or use default"),
            ],
        },
        module! {
            name: "test",
            page: "test.md",
            call: core::call_test,
            rows: [
                u("fn assert(condition: Bool, message: String) -> ()", "Assert value is truthy").optional_last(),
                u("fn assert_eq(left: a, right: a, message: String) -> () where a: Equal + Display", "Assert two values are equal").optional_last(),
                u("fn assert_ne(left: a, right: a, message: String) -> () where a: Equal + Display", "Assert two values are not equal").optional_last(),
            ],
        },
        module! {
            name: "channel",
            page: "channel-task.md",
            types: "\
                pub type ChannelResult(a) { Message(a), Closed, Sent, Empty }\n\
                pub type ChannelOp(a) { Recv(Channel(a)), Send(Channel(a), a) }\n\
                pub type ChannelError { ChannelTimeout, ChannelClosed }\n\
            ",
            derives: [("ChannelOp", &[])],
            error: "ChannelError",
            steps: concurrency::call_channel,
            rows: [
                u("fn close(ch: Channel(a)) -> ()", "Close the channel"),
                u("fn each(ch: Channel(a), f: Fn(a) -> b) -> ()", "Iterate until channel closes"),
                u("fn new(capacity: Int) -> Channel(a)", "Create a channel (0 = rendezvous, N = buffered)").optional_last(),
                u("fn receive(ch: Channel(a)) -> ChannelResult(a)", "Blocking receive"),
                u("fn recv_timeout(ch: Channel(a), dur: Duration) -> Result(a, ChannelError)", "Blocking receive with a timeout"),
                u("fn select(ops: List(ChannelOp(a))) -> (Channel(a), ChannelResult(a))", "Wait on multiple channels (each op is `Recv(ch)` or `Send(ch, v)`)"),
                u("fn send(ch: Channel(a), value: a) -> ()", "Blocking send"),
                u("fn timeout(ms: Int) -> Channel(a)", "Create a channel that closes after N ms"),
                u("fn try_receive(ch: Channel(a)) -> ChannelResult(a)", "Non-blocking receive"),
                u("fn try_send(ch: Channel(a), value: a) -> Bool", "Non-blocking send"),
            ],
        },
        module! {
            name: "task",
            page: "channel-task.md",
            opaque: [("Handle", 1)],
            steps: concurrency::call_task,
            rows: [
                u("fn cancel(handle: Handle(a)) -> ()", "Request cancellation of a task (cooperative; see details below)"),
                u("fn deadline(dur: Duration, f: Fn() -> a) -> a", "Run a callback with a scoped I/O deadline"),
                u("fn join(handle: Handle(a)) -> a", "Wait for a task to complete"),
                u("fn spawn(f: Fn() -> a) -> Handle(a)", "Spawn a new lightweight task"),
                u("fn spawn_until(dur: Duration, f: Fn() -> a) -> Handle(a)", "Spawn a task scoped by a deadline"),
            ],
        },
        module! {
            name: "regex",
            page: "regex.md",
            types: "\
                pub type RegexError { RegexInvalidPattern(String, Int), RegexTooBig }\n\
            ",
            error: "RegexError",
            steps: regex::call_regex,
            rows: [
                u("fn captures(pattern: String, text: String) -> Option(List(String))", "Capture groups from first match"),
                u("fn captures_all(pattern: String, text: String) -> List(List(String))", "Capture groups from all matches"),
                u("fn captures_named(pattern: String, text: String) -> Option(Map(String, String))", "Named capture groups from first match"),
                u("fn find(pattern: String, text: String) -> Option(String)", "First match"),
                u("fn find_all(pattern: String, text: String) -> List(String)", "All matches"),
                u("fn is_match(pattern: String, text: String) -> Bool", "Test if pattern matches"),
                u("fn replace(pattern: String, text: String, replacement: String) -> String", "Replace first match"),
                u("fn replace_all(pattern: String, text: String, replacement: String) -> String", "Replace all matches"),
                u("fn replace_all_with(pattern: String, text: String, f: Fn(String) -> String) -> String", "Replace all with callback"),
                u("fn split(pattern: String, text: String) -> List(String)", "Split on pattern"),
            ],
        },
        module! {
            name: "json",
            page: "json.md",
            types: "\
                pub type JsonError { JsonSyntax(String, Int), JsonTypeMismatch(String, String), JsonMissingField(String), JsonUnknown(String) }\n\
            ",
            error: "JsonError",
            call: json::call_json,
            rows: [
                u("fn parse(s: String, type a) -> Result(a, JsonError)", "Parse JSON object into record"),
                u("fn parse_list(s: String, type a) -> Result(List(a), JsonError)", "Parse JSON array into record list"),
                u("fn parse_map(s: String, type a) -> Result(Map(String, a), JsonError)", "Parse JSON object into map"),
                u("fn pretty(value: a) -> String", "Pretty-print value as JSON"),
                u("fn stringify(value: a) -> String", "Serialize value as compact JSON"),
            ],
        },
        module! {
            name: "toml",
            page: "toml.md",
            types: "\
                pub type TomlError { TomlSyntax(String, Int), TomlTypeMismatch(String, String), TomlMissingField(String), TomlUnknown(String) }\n\
            ",
            error: "TomlError",
            call: toml::call,
            rows: [
                u("fn parse(s: String, type a) -> Result(a, TomlError)", "Parse a TOML document (top-level table) into a record"),
                u("fn parse_list(s: String, type a) -> Result(List(a), TomlError)", "Parse a single `[[items]]` section into a list of records"),
                u("fn parse_map(s: String, type a) -> Result(Map(String, a), TomlError)", "Parse a top-level table into a map"),
                u("fn pretty(value: a) -> Result(String, TomlError)", "Pretty-print a value as TOML"),
                u("fn stringify(value: a) -> Result(String, TomlError)", "Serialize a value as TOML"),
            ],
        },
        module! {
            name: "set",
            page: "set.md",
            steps: collections::call_set,
            rows: [
                u("fn contains(s: Set(a), elem: a) -> Bool where a: Hash", "Check membership"),
                u("fn difference(a: Set(a), b: Set(a)) -> Set(a)", "Elements in first but not second"),
                u("fn each(s: Set(a), f: Fn(a) -> ()) -> ()", "Iterate over all elements"),
                u("fn filter(s: Set(a), f: Fn(a) -> Bool) -> Set(a)", "Keep elements matching predicate"),
                u("fn fold(s: Set(a), init: b, f: Fn(b, a) -> b) -> b", "Reduce to a single value"),
                u("fn from_list(xs: List(a)) -> Set(a) where a: Hash", "Create set from list"),
                u("fn insert(s: Set(a), elem: a) -> Set(a) where a: Hash", "Add an element"),
                u("fn intersection(a: Set(a), b: Set(a)) -> Set(a)", "Elements in both sets"),
                u("fn is_subset(a: Set(a), b: Set(a)) -> Bool", "True if first is subset of second"),
                u("fn length(s: Set(a)) -> Int", "Number of elements"),
                u("fn map(s: Set(a), f: Fn(a) -> b) -> Set(b) where b: Hash", "Transform each element"),
                u("fn new() -> Set(a)", "Create an empty set"),
                u("fn remove(s: Set(a), elem: a) -> Set(a) where a: Hash", "Remove an element"),
                u("fn symmetric_difference(a: Set(a), b: Set(a)) -> Set(a)", "Elements in exactly one of the two sets"),
                u("fn to_list(s: Set(a)) -> List(a)", "Convert set to sorted list"),
                u("fn union(a: Set(a), b: Set(a)) -> Set(a)", "Combine all elements"),
            ],
        },
        module! {
            name: "math",
            page: "math.md",
            call: numeric::call_math,
            rows: [
                u("fn acos(x: Float) -> Float", "Arccosine (radians)"),
                u("fn asin(x: Float) -> Float", "Arcsine (radians)"),
                u("fn atan(x: Float) -> Float", "Arctangent (radians)"),
                u("fn atan2(y: Float, x: Float) -> Float", "Two-argument arctangent"),
                u("fn cos(x: Float) -> Float", "Cosine"),
                k("e: Float", "Euler's number (2.71828...)", std::f64::consts::E),
                u("fn exp(x: Float) -> Float", "Exponential (e^x)"),
                u("fn log(x: Float) -> Float", "Natural logarithm (ln)"),
                u("fn log10(x: Float) -> Float", "Base-10 logarithm"),
                k("pi: Float", "Pi (3.14159...)", std::f64::consts::PI),
                u("fn pow(base: Float, exponent: Float) -> Float", "Exponentiation"),
                u("fn random() -> Float", "Random float in [0.0, 1.0)"),
                u("fn sin(x: Float) -> Float", "Sine"),
                u("fn sqrt(x: Float) -> Float", "Square root"),
                u("fn tan(x: Float) -> Float", "Tangent"),
            ],
        },
        module! {
            name: "time",
            page: "time.md",
            types: "\
                pub type Instant { epoch_ns: Int }\n\
                pub type Date { year: Int, month: Int, day: Int }\n\
                pub type Time { hour: Int, minute: Int, second: Int, ns: Int }\n\
                pub type DateTime { date: Date, time: Time }\n\
                pub type Duration { ns: Int }\n\
                pub type Weekday { Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday }\n\
                pub type TimeError { TimeParseFormat(String), TimeOutOfRange(String) }\n\
            ",
            error: "TimeError",
            steps: time::call_time,
            rows: [
                u("fn now() -> Instant", "Current UTC time as nanosecond epoch"),
                u("fn today() -> Date", "Current local date"),
                u("fn date(year: Int, month: Int, day: Int) -> Result(Date, TimeError)", "Validated date from year, month, day"),
                u("fn time(hour: Int, min: Int, sec: Int) -> Result(Time, TimeError)", "Validated time from hour, min, sec (ns=0)"),
                u("fn datetime(date: Date, time: Time) -> DateTime", "Combine date and time (infallible)"),
                u("fn to_datetime(instant: Instant, offset_minutes: Int) -> DateTime", "Convert instant to local datetime with UTC offset in minutes"),
                u("fn to_instant(datetime: DateTime, offset_minutes: Int) -> Instant", "Convert local datetime to instant with UTC offset in minutes"),
                u("fn to_utc(instant: Instant) -> DateTime", "Convert instant to UTC datetime (shorthand for offset=0)"),
                u("fn from_utc(datetime: DateTime) -> Instant", "Convert UTC datetime to instant (shorthand for offset=0)"),
                u("fn format(datetime: DateTime, pattern: String) -> String", "Format datetime with strftime pattern"),
                u("fn format_date(date: Date, pattern: String) -> String", "Format date with strftime pattern"),
                u("fn parse(s: String, pattern: String) -> Result(DateTime, TimeError)", "Parse string into datetime with strftime pattern"),
                u("fn parse_date(s: String, pattern: String) -> Result(Date, TimeError)", "Parse string into date with strftime pattern"),
                u("fn add_days(date: Date, days: Int) -> Date", "Add/subtract days from a date"),
                u("fn add_months(date: Date, months: Int) -> Date", "Add/subtract months, clamping to end-of-month"),
                u("fn add(instant: Instant, duration: Duration) -> Instant", "Add duration to an instant"),
                u("fn since(from: Instant, to: Instant) -> Duration", "Signed duration between two instants (to − from)"),
                u("fn hours(n: Int) -> Duration", "Create duration from hours"),
                u("fn minutes(n: Int) -> Duration", "Create duration from minutes"),
                u("fn seconds(n: Int) -> Duration", "Create duration from seconds"),
                u("fn ms(n: Int) -> Duration", "Create duration from milliseconds"),
                u("fn micros(n: Int) -> Duration", "Create duration from microseconds"),
                u("fn nanos(n: Int) -> Duration", "Create duration from nanoseconds"),
                u("fn weekday(date: Date) -> Weekday", "Day of the week"),
                u("fn days_between(from: Date, to: Date) -> Int", "Signed number of days between two dates"),
                u("fn days_in_month(year: Int, month: Int) -> Int", "Days in month for given year and month"),
                u("fn is_leap_year(year: Int) -> Bool", "Check if a year is a leap year"),
                u("fn sleep(duration: Duration) -> ()", "Fiber-aware sleep"),
            ],
        },
        module! {
            name: "http",
            page: "http.md",
            types: "\
                pub type Method { GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS }\n\
                pub type Response { status: Int, body: String, headers: Map(String, String) }\n\
                pub type Request { method: Method, path: String, query: String, headers: Map(String, String), body: String }\n\
                pub type HttpError { HttpConnect(String), HttpTls(String), HttpTimeout, HttpInvalidUrl(String), HttpInvalidResponse(String), HttpClosedEarly, HttpStatusCode(Int, String), HttpUnknown(String) }\n\
            ",
            derives: [("Response", &["Equal", "Hash", "Display"]), ("Request", &["Equal", "Hash", "Display"])],
            error: "HttpError",
            steps: http::call_http,
            rows: [
                u("fn get(url: String) -> Result(Response, HttpError)", "HTTP GET request").feature("http", cfg!(feature = "http")),
                u("fn request(method: Method, url: String, body: String, headers: Map(String, String)) -> Result(Response, HttpError)", "HTTP request with method, URL, body, headers").feature("http", cfg!(feature = "http")),
                u("fn serve(listener: TcpListener, handler: Fn(Request) -> Response) -> ()", "Serve HTTP on a listener made with `tcp.listen`, a task per connection").feature("http", cfg!(feature = "http")),
                u("fn segments(path: String) -> List(String)", "Split URL path into segments"),
                u("fn parse_query(query: String) -> Map(String, List(String))", "Parse a URL query string into a multi-value map"),
            ],
        },
        module! {
            name: "fs",
            page: "io-fs.md",
            types: "\
                pub type FileStat { size: Int, is_file: Bool, is_dir: Bool, is_symlink: Bool, modified: Int, readonly: Bool, mode: Int, accessed: Option(DateTime), created: Option(DateTime) }\n\
            ",
            call: io::call_fs,
            rows: [
                u("fn copy(from: String, to: String) -> Result((), IoError)", "Copy a file"),
                u("fn exists(path: String) -> Bool", "Check if path exists"),
                u("fn glob(pattern: String) -> Result(List(String), IoError)", "Match paths by glob pattern"),
                u("fn is_dir(path: String) -> Bool", "Check if path is a directory"),
                u("fn is_file(path: String) -> Bool", "Check if path is a file"),
                u("fn is_symlink(path: String) -> Bool", "Check if path is a symlink (without following)"),
                u("fn list_dir(path: String) -> Result(List(String), IoError)", "List entries in a directory"),
                u("fn mkdir(path: String) -> Result((), IoError)", "Create a directory (and parents)"),
                u("fn read_link(path: String) -> Result(String, IoError)", "Read a symlink's target (without following)"),
                u("fn remove(path: String) -> Result((), IoError)", "Remove a file or empty directory"),
                u("fn rename(from: String, to: String) -> Result((), IoError)", "Rename / move a file or directory"),
                u("fn stat(path: String) -> Result(FileStat, IoError)", "Fetch filesystem metadata for a path"),
                u("fn walk(root: String) -> Result(List(String), IoError)", "Recursively list all paths under a directory"),
            ],
        },
        module! {
            name: "env",
            page: "io-fs.md",
            call: io::call_env,
            rows: [
                u("fn get(key: String) -> Option(String)", "Read an environment variable"),
                u("fn set(key: String, value: String) -> ()", "Set an environment variable"),
                u("fn remove(name: String) -> ()", "Unset an environment variable (idempotent)"),
                u("fn vars() -> List((String, String))", "Snapshot every environment variable"),
            ],
        },
        module! {
            name: "postgres",
            feature: "postgres",
            page: "postgres.md",
            types: "\
                pub type PgError { PgConnect(String), PgTls(String), PgAuthFailed(String), PgQuery(String, String), PgTypeMismatch(String, String, String), PgNoSuchColumn(String), PgClosed, PgTimeout, PgTxnAborted, PgUnknown(String) }\n\
            ",
            opaque: [("PgPool", 0), ("PgTx", 0), ("PgCursor", 0), ("QueryResult", 0), ("ExecResult", 0), ("Value", 0)],
            error: "PgError",
            steps: postgres::call,
            rows: [
                u("fn connect(url: String) -> Result(PgPool, PgError)", "Open a connection pool from a `postgresql://` URL (uses r2d2 defaults)"),
                u("fn connect_with(url: String, opts: Map(String, Int)) -> Result(PgPool, PgError)", "Like `connect` with a tunable options bag (see [Connect options](#connect-options))"),
                u("fn query(conn: a, sql: String, params: List(Value)) -> Result(QueryResult, PgError)", "Run a SELECT-style statement and materialize rows"),
                u("fn execute(conn: a, sql: String, params: List(Value)) -> Result(ExecResult, PgError)", "Run an INSERT/UPDATE/DELETE and return affected-row count"),
                u("fn transact(pool: PgPool, f: Fn(PgTx) -> Result(a, PgError)) -> Result(a, PgError)", "Pin a single connection for a transaction; callback runs inside BEGIN/COMMIT"),
                u("fn close(pool: PgPool) -> ()", "Drop the pool; future ops on it error"),
                u("fn stream(conn: a, sql: String, params: List(Value)) -> Result(Channel(b), PgError)", "Stream rows through a bounded channel (backpressured)"),
                u("fn cursor(tx: PgTx, sql: String, params: List(Value), batch_size: Int) -> Result(PgCursor, PgError)", "Declare a server-side cursor with batch size"),
                u("fn cursor_next(cursor: PgCursor) -> Result(List(Map(String, Value)), PgError)", "Fetch the next batch of rows from a cursor"),
                u("fn cursor_close(cursor: PgCursor) -> Result((), PgError)", "Release a cursor and its underlying connection"),
                u("fn listen(pool: PgPool, channel: String) -> Result(Channel(a), PgError)", "LISTEN on a channel; delivers async notifications"),
                u("fn notify(conn: a, channel: String, payload: String) -> Result((), PgError)", "NOTIFY a channel with a payload"),
                u("fn uuidv7() -> String", "Generate a time-ordered UUIDv7 (RFC 9562)"),
            ],
        },
        module! {
            name: "bytes",
            page: "bytes.md",
            types: "\
                pub type BytesError { BytesInvalidUtf8(Int), BytesInvalidHex(String), BytesInvalidBase64(String), BytesByteOutOfRange(Int), BytesOutOfBounds(Int) }\n\
            ",
            error: "BytesError",
            call: bytes::call,
            rows: [
                u("fn concat(a: Bytes, b: Bytes) -> Bytes", "Concatenate two byte sequences"),
                u("fn concat_all(parts: List(Bytes)) -> Bytes", "Concatenate every element of a list"),
                u("fn empty() -> Bytes", "Zero-length byte sequence"),
                u("fn ends_with(b: Bytes, suffix: Bytes) -> Bool", "True if `b` ends with `suffix`"),
                u("fn eq(a: Bytes, b: Bytes) -> Bool", "Structural byte-by-byte comparison"),
                u("fn from_base64(s: String) -> Result(Bytes, BytesError)", "Decode base64 string"),
                u("fn from_hex(s: String) -> Result(Bytes, BytesError)", "Decode hex string (case-insensitive)"),
                u("fn from_list(xs: List(Int)) -> Result(Bytes, BytesError)", "Build from a list of byte values (0..=255)"),
                u("fn from_string(s: String) -> Bytes", "UTF-8 encode a string"),
                u("fn get(b: Bytes, i: Int) -> Result(Int, BytesError)", "Read a single byte at index"),
                u("fn index_of(b: Bytes, needle: Bytes) -> Option(Int)", "First offset at which `needle` appears"),
                u("fn length(b: Bytes) -> Int", "Number of bytes"),
                u("fn slice(b: Bytes, start: Int, end: Int) -> Result(Bytes, BytesError)", "Half-open `[start, end)` slice"),
                u("fn split(b: Bytes, sep: Bytes) -> List(Bytes)", "Split on every occurrence of `sep` (panics if `sep` is empty)"),
                u("fn starts_with(b: Bytes, prefix: Bytes) -> Bool", "True if `b` begins with `prefix`"),
                u("fn to_base64(b: Bytes) -> String", "Encode as base64"),
                u("fn to_hex(b: Bytes) -> String", "Encode as lowercase hex"),
                u("fn to_list(b: Bytes) -> List(Int)", "Materialize as a list of byte values"),
                u("fn to_string(b: Bytes) -> Result(String, BytesError)", "UTF-8 decode (errors on invalid UTF-8)"),
            ],
        },
        module! {
            name: "crypto",
            page: "crypto.md",
            call: crypto::call,
            rows: [
                u("fn sha256(data: Bytes) -> Bytes", "SHA-256 digest (32 bytes)"),
                u("fn sha512(data: Bytes) -> Bytes", "SHA-512 digest (64 bytes)"),
                u("fn md5(data: Bytes) -> Bytes", "MD5 digest (16 bytes) — **legacy / non-security use only**"),
                u("fn md5_hex(data: Bytes) -> String", "MD5 digest as lower-case hex (32 chars)"),
                u("fn blake2b(data: Bytes) -> Bytes", "BLAKE2b-512 digest (64 bytes), RFC 7693"),
                u("fn blake2b_hex(data: Bytes) -> String", "BLAKE2b-512 digest as lower-case hex (128 chars)"),
                u("fn hmac_sha256(key: Bytes, msg: Bytes) -> Bytes", "HMAC-SHA256 over `(key, msg)` (32 bytes)"),
                u("fn hmac_sha512(key: Bytes, msg: Bytes) -> Bytes", "HMAC-SHA512 over `(key, msg)` (64 bytes)"),
                u("fn random_bytes(n: Int) -> Result(Bytes, String)", "OS CSPRNG, `0..=1_048_576` bytes"),
                u("fn constant_time_eq(a: Bytes, b: Bytes) -> Bool", "Timing-safe comparison (lengths leak)"),
            ],
        },
        module! {
            name: "encoding",
            page: "encoding.md",
            call: encoding::call,
            rows: [
                u("fn url_encode(s: String) -> String", "Percent-encode per RFC 3986 (unreserved = `ALPHA` / `DIGIT` / `-._~`)"),
                u("fn url_decode(s: String) -> Result(String, String)", "Inverse. Errors on malformed `%HH` or invalid UTF-8 after decoding"),
                u("fn form_encode(pairs: List((String, String))) -> String", "Build an `application/x-www-form-urlencoded` body"),
                u("fn form_decode(body: String) -> Result(List((String, String)), String)", "Parse an `application/x-www-form-urlencoded` body into pairs"),
            ],
        },
        module! {
            name: "tcp",
            feature: "tcp",
            page: "tcp.md",
            types: "\
                pub type TcpError { TcpConnect(String), TcpTls(String), TcpClosed, TcpTimeout, TcpUnknown(String) }\n\
            ",
            opaque: [("TcpListener", 0), ("TcpStream", 0)],
            error: "TcpError",
            steps: tcp::call,
            rows: [
                u("fn accept(listener: TcpListener) -> Result(TcpStream, TcpError)", "Wait for an incoming connection (cooperative I/O)"),
                u("fn close(stream: TcpStream) -> ()", "Shut the connection down: operations in flight on it return, later ones give `Err(TcpClosed)`"),
                u("fn connect(addr: String) -> Result(TcpStream, TcpError)", "Open a TCP connection to `host:port` (cooperative I/O)"),
                u("fn listen(addr: String) -> Result(TcpListener, TcpError)", "Bind a TCP listener to `host:port`"),
                u("fn local_port(listener: TcpListener) -> Int", "The port the listener is bound to: the one the system chose for port `0`"),
                u("fn peer_addr(stream: TcpStream) -> Result(String, TcpError)", "The address of the other end, as `ip:port`"),
                u("fn read(stream: TcpStream, max: Int) -> Result(Bytes, TcpError)", "Read up to `max` bytes (cooperative)"),
                u("fn read_exact(stream: TcpStream, n: Int) -> Result(Bytes, TcpError)", "Read exactly `n` bytes (cooperative; loops)"),
                u("fn set_nodelay(stream: TcpStream, on: Bool) -> Result((), TcpError)", "Send small writes at once (`true`) instead of gathering them (Nagle's algorithm, the default)"),
                u("fn write(stream: TcpStream, data: Bytes) -> Result((), TcpError)", "Write the entire buffer and flush (cooperative)"),
                u("fn accept_tls(listener: TcpListener, cert_pem: Bytes, key_pem: Bytes) -> Result(TcpStream, TcpError)", "Accept a connection and complete the TLS server handshake using the supplied PEM cert chain + key").feature("tcp-tls", cfg!(feature = "tcp-tls")),
                u("fn accept_tls_mtls(listener: TcpListener, cert_pem: Bytes, key_pem: Bytes, client_ca_pem: Bytes) -> Result(TcpStream, TcpError)", "Like `accept_tls`, but also requires the client to present a cert chaining to the supplied CA PEM bundle (mutual TLS)").feature("tcp-tls", cfg!(feature = "tcp-tls")),
                u("fn connect_tls(addr: String, hostname: String) -> Result(TcpStream, TcpError)", "Open a TCP connection then complete the TLS client handshake against `hostname`").feature("tcp-tls", cfg!(feature = "tcp-tls")),
            ],
        },
        module! {
            name: "stream",
            page: "stream.md",
            steps: stream::call,
            rows: [
                u("fn from_list(xs: List(a)) -> Channel(a)", "Emit list elements then close"),
                u("fn from_range(lo: Int, hi: Int) -> Channel(Int)", "Emit `lo..=hi` then close"),
                u("fn repeat(x: a) -> Channel(a)", "Infinite — pair with `take`"),
                u("fn unfold(seed: a, f: Fn(a) -> Option((b, a))) -> Channel(b)", "Generator (closes on `None`)"),
                u("fn file_chunks(path: String, size: Int) -> Channel(Result(Bytes, IoError))", "Read file in chunks"),
                u("fn file_lines(path: String) -> Channel(Result(String, IoError))", "Read file line-by-line"),
                u("fn tcp_chunks(stream: TcpStream, size: Int) -> Channel(Result(Bytes, TcpError))", "Read TCP in chunks").feature("tcp", cfg!(feature = "tcp")),
                u("fn tcp_lines(stream: TcpStream) -> Channel(Result(String, TcpError))", "Read TCP line-by-line").feature("tcp", cfg!(feature = "tcp")),
                u("fn map(ch: Channel(a), f: Fn(a) -> b) -> Channel(b)", "Apply `f` to each element"),
                u("fn map_ok(ch: Channel(Result(a, b)), f: Fn(a) -> c) -> Channel(Result(c, b))", "Apply `f` to each `Ok` element; `Err` passes through"),
                u("fn filter(ch: Channel(a), pred: Fn(a) -> Bool) -> Channel(a)", "Keep the elements `pred` accepts"),
                u("fn filter_ok(ch: Channel(Result(a, b)), pred: Fn(a) -> Bool) -> Channel(Result(a, b))", "Keep the `Ok` elements `pred` accepts; `Err` passes through"),
                u("fn flat_map(ch: Channel(a), f: Fn(a) -> List(b)) -> Channel(b)", "Emit each element of `f(x)`"),
                u("fn take(ch: Channel(a), n: Int) -> Channel(a)", "The first `n` elements"),
                u("fn drop(ch: Channel(a), n: Int) -> Channel(a)", "Skip the first `n` elements"),
                u("fn take_while(ch: Channel(a), pred: Fn(a) -> Bool) -> Channel(a)", "Elements until `pred` first rejects one"),
                u("fn drop_while(ch: Channel(a), pred: Fn(a) -> Bool) -> Channel(a)", "Skip elements until `pred` first rejects one"),
                u("fn chunks(ch: Channel(a), n: Int) -> Channel(List(a))", "Group elements into lists of `n`"),
                u("fn scan(ch: Channel(a), init: b, f: Fn(b, a) -> b) -> Channel(b)", "Running fold: emit each accumulator"),
                u("fn dedup(ch: Channel(a)) -> Channel(a) where a: Equal", "Drop consecutive duplicates"),
                u("fn buffered(ch: Channel(a), n: Int) -> Channel(a)", "Decouple producer and consumer with a buffer of `n`"),
                u("fn merge(chs: List(Channel(a))) -> Channel(a)", "Interleave several streams as elements arrive"),
                u("fn concat(chs: List(Channel(a))) -> Channel(a)", "One stream after another"),
                u("fn zip(a: Channel(a), b: Channel(b)) -> Channel((a, b))", "Pair elements of two streams"),
                u("fn collect(ch: Channel(a)) -> List(a)", "Drain into a list"),
                u("fn fold(ch: Channel(a), init: b, f: Fn(b, a) -> b) -> b", "Reduce to a single value"),
                u("fn each(ch: Channel(a), f: Fn(a) -> ()) -> ()", "Call `f` for each element"),
                u("fn count(ch: Channel(a)) -> Int", "Count the elements"),
                u("fn first(ch: Channel(a)) -> Option(a)", "The first element, or `None`"),
                u("fn last(ch: Channel(a)) -> Option(a)", "The last element, or `None`"),
                u("fn write_to_file(ch: Channel(Bytes), path: String) -> Result((), IoError)", "Write each chunk to a file"),
                u("fn write_to_tcp(ch: Channel(Bytes), stream: TcpStream) -> Result((), TcpError)", "Write each chunk to a TCP stream").feature("tcp", cfg!(feature = "tcp")),
            ],
        },
        module! {
            name: "uuid",
            page: "uuid.md",
            call: uuid::call,
            rows: [
                u("fn v4() -> String", "Random UUID (version 4, CSPRNG-backed)"),
                u("fn v7() -> String", "Time-ordered UUID (version 7, RFC 9562)"),
                u("fn parse(s: String) -> Result(String, String)", "Validate + canonicalize any-version UUID"),
                u("fn nil() -> String", "The all-zero UUID sentinel"),
                u("fn is_valid(s: String) -> Bool", "Predicate form of `parse`"),
            ],
        },
    ]
}
