//! Test suite: documentation, parity and source-text checks.
//!
//! One test binary; each module was a separate test crate before.

mod builtin_docs_frontmatter_tests;
mod docs_markdown_println_parity_tests;
mod docs_math_display_tests;
mod docs_primitive_descriptor_list_tests;
mod docs_round26_tests;
mod docs_round88_modules_placeholder_not_stdlib_tests;
mod docs_round88_supervisor_runs_tests;
mod editor_grammar_builtins_tests;
mod editor_grammar_constructors_tests;
mod editor_grammar_keywords_tests;
mod editor_grammar_modules_tests;
mod editor_grammar_number_literals_tests;
mod editor_grammar_primitives_tests;
mod editor_grammar_string_escapes_tests;
mod formatter_inline_block_tests;
mod keyword_list_parity_tests;
mod lexer_keyword_parity_tests;
mod release_asset_name_parity_tests;
mod release_version_drift_tests;
mod round100_formatter_block_comment_dup_tests;
mod round101_features_footer_cargo_parity_tests;
mod round101_normalize_path_dedup_tests;
mod round101_pattern_binder_walker_parity_lock_tests;
mod round62_cleanup_lock_tests;
mod round69_followup_lock_tests;
mod round69_formatter_scanner_collapse_lock_tests;
mod round69_misc_lock_tests;
mod round71_doc_drift_lock_tests;
mod round73_formatter_collection_dedup_tests;
mod round75_dead_code_locks_tests;
mod round75_typechecker_remap_and_dedup_tests;
mod round79_doc_frontmatter_parity_tests;
mod round80_dead_code_tests;
mod round80_doc_top_level_order_tests;
mod round81_formatter_binop_bp_parity_tests;
mod round83_dead_code_dedup_lock_tests;
mod round84_readme_keyword_parity_tests;
mod round86_editor_grammar_operators_lexer_parity_tests;
mod round88_formatter_precedence_dedup_lock_tests;
mod rustdoc_warnings_lock_tests;
mod stdlib_reference_tests;
