//! Lock file (`silt.lock`) reading and writing.
//!
//! A silt lockfile pins each transitive dependency of the local package
//! to a specific source location and a content checksum. The file lives
//! next to the `silt.toml` it belongs to and is regenerated when the
//! manifest changes (auto-update) or on demand via `silt update`. The
//! dependency graph itself is resolved in `package_graph`, always from
//! the manifests: the lock only pins the commit a git branch or tag
//! resolved to, and an entry that is not what the manifest resolves to
//! is stale. It never decides where a package comes from.
//!
//! Supported source forms (as of v0.8): `LockedSource::Path` for path
//! deps and `LockedSource::Git` for git deps (`{ url, ref_spec,
//! resolved_sha }`). Future phases will add `Registry { name, version }`
//! without requiring a schema-version bump (consumers default to
//! "unknown source" and bail out if they don't recognise the variant —
//! see the TOML write/parse path below).
//!
//! # Layout
//!
//! ```toml
//! # This file is generated by silt. Do not edit by hand.
//! version = 1
//!
//! [[package]]
//! name = "my_app"
//! version = "0.1.0"
//!
//! [[package]]
//! name = "calc"
//! version = "0.1.0"
//! source = { path = "/canonical/path/to/calc" }
//! checksum = "sha256:..."
//!
//! [[package]]
//! name = "remote"
//! version = "0.1.0"
//! source = { git = "https://example.com/r.git", branch = "main", rev = "<40-hex>" }
//! checksum = "sha256:..."
//! ```
//!
//! The local package gets an entry with no `source` or `checksum` (it
//! is the root of the dep graph; nothing pins *it*). All other entries
//! must carry both fields.
//!
//! # Why not `toml::to_string`?
//!
//! We render the lockfile manually rather than reaching for a TOML
//! serializer. Two reasons:
//!   - The current `toml` crate dep is configured `default-features =
//!     false, features = ["parse"]` — adding `display` would pull in
//!     extra serialization machinery we don't otherwise need.
//!   - Stable, deterministic output (sorted by name, fixed key order,
//!     literal "do not edit" header) is easier to produce by hand than
//!     to coax out of a generic serializer. The format is small enough
//!     (≤6 fields per package) that the manual writer is trivial.

use std::fs;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

use crate::diagnostic::{Code, Diagnostic};
use crate::git::{self, GitRef};
use crate::manifest::{display_path, toml_error_message};
use crate::source::{SourceMap, SourceName, Span};

// ── Public types ───────────────────────────────────────────────────────

/// Top-level lockfile contents.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Lockfile {
    /// Schema version. Currently always `1`. Bumped on incompatible
    /// changes; the parser refuses unknown versions so old binaries
    /// don't silently misread a newer file.
    pub version: u32,
    /// All packages in the dep graph, including the local (root)
    /// package. Sorted by name for stable output.
    pub packages: Vec<LockedPackage>,
}

/// One pinned package entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockedPackage {
    /// Package name as written in its own `silt.toml` `[package].name`.
    pub name: String,
    /// Package version (semver string, validated by manifest loader).
    pub version: String,
    /// Where the package was resolved from. `Local` for the root —
    /// nothing pins the local package, so it has no source/checksum.
    pub source: LockedSource,
    /// Content hash of the dep's source tree (`"sha256:<hex>"`),
    /// computed by `checksum_path_source` (internal). Empty for the root.
    pub checksum: String,
}

/// Where a locked package lives. The root entry uses `Local`; transitive
/// deps use `Path` or `Git`. `Registry` will land in a later phase.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LockedSource {
    /// Marker for the local (root) package — no `source` or `checksum`
    /// in the on-disk file.
    Local,
    /// Path-style dependency. `path` is the canonical path of the
    /// package root, so the lockfile is portable across cwd changes
    /// (you still pay the price of moving the workspace, of course;
    /// that's a known limitation of path deps).
    Path { path: PathBuf },
    /// Git-style dependency. `url` is the manifest's URL with a local
    /// path made absolute against the manifest's directory; it and the
    /// user's chosen `ref_spec` are preserved so `silt update` can
    /// re-resolve branch/tag deps; `resolved_sha` is the full commit id
    /// pinned at lock time.
    Git {
        url: String,
        ref_spec: GitRef,
        resolved_sha: String,
    },
    // Future: Registry { name, version }.
}

impl Lockfile {
    /// Load the lockfile at `path`, adding its text to `sources`.
    /// `Ok(None)` when there is no file. A file that is not a lockfile
    /// is a diagnostic in it.
    pub fn load(path: &Path, sources: &mut SourceMap) -> Result<Option<Lockfile>, Diagnostic> {
        let text = match fs::read_to_string(path) {
            Ok(text) => text,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            Err(e) => {
                let file = sources.add(SourceName::Manifest(display_path(path)), "".into());
                return Err(Diagnostic::error(
                    Code::PackageIo,
                    Span::point(file, 0),
                    format!(
                        "cannot read lockfile: {}",
                        git::escape_for_display(&crate::diagnostic::io_error_text(&e))
                    ),
                ));
            }
        };
        // A lockfile is shown as a manifest is: its lines by the display
        // rule, since it can be edited by hand.
        let file = sources.add(
            SourceName::Manifest(display_path(path)),
            text.as_str().into(),
        );
        parse_lockfile(&text).map(Some).map_err(|e| {
            let span = Span {
                file,
                start: e.span.0 as u32,
                end: e.span.1 as u32,
            };
            let mut lines = e.message.lines().map(git::escape_for_display);
            let head = lines.next().unwrap_or_default();
            let mut d = Diagnostic::error(
                Code::LockfileInvalid,
                span,
                format!("invalid lockfile: {head}"),
            );
            d.notes.extend(lines);
            d.with_help("delete silt.lock and run `silt update` to write it again")
        })
    }

    /// Write the lockfile to disk in stable TOML format.
    ///
    /// Output is deterministic: a fixed header, packages sorted by
    /// name, fixed key order within each entry. This makes lockfiles
    /// git-friendly — a no-op `silt update` produces a byte-identical
    /// file.
    pub fn write(&self, path: &Path) -> std::io::Result<()> {
        fs::write(path, render_lockfile(self))
    }

    /// Whether `self` pins what `other` pins: the same packages with
    /// the same versions and sources. Checksums are not compared:
    /// content drift in a path dep is what `silt update` is for.
    pub fn same_pins(&self, other: &Lockfile) -> bool {
        let key = |lock: &Lockfile| {
            let mut entries: Vec<(String, String, LockedSource)> = lock
                .packages
                .iter()
                .map(|p| (p.name.clone(), p.version.clone(), p.source.clone()))
                .collect();
            entries.sort_by(|a, b| a.0.cmp(&b.0));
            entries
        };
        key(self) == key(other)
    }
}

/// Why the sources of a dependency cannot be checksummed.
#[derive(Debug)]
pub enum ChecksumError {
    Io(std::io::Error),
    /// A symbolic link at this path, relative to the package root.
    Symlink(PathBuf),
}

/// Compute a content-hash over a path-dep's source tree.
///
/// Walks `<pkg_root>/src/` recursively, hashes every `.silt` file's
/// contents, then folds those into a single SHA-256 keyed by relative
/// path. The encoding (`"{relpath}\0{filehash}\n"`) is unambiguous even
/// across paths containing newlines or NUL — neither is legal in silt
/// module names but the encoding stays robust regardless.
///
/// Excluded by virtue of not walking them: `silt.lock`, `target/`,
/// `.git/`. Sticking to `src/` makes the checksum mean exactly "the
/// sources the compiler will see".
///
/// This walk is also the one symlink rule for a dependency, path or git
/// alike: `silt.toml` and everything under `src/` (`src` itself
/// included) must be the package's own files, never a link to somewhere
/// else on the machine. A link there is an error, not followed. Links
/// elsewhere in the package are never read and so are allowed, and so is
/// a dependency root that is itself reached through a link
/// (`dep = { path = "../dep" }` with `../dep` a link to a directory).
pub fn checksum_path_source(pkg_root: &Path) -> Result<String, ChecksumError> {
    if fs::symlink_metadata(pkg_root.join("silt.toml")).is_ok_and(|m| m.file_type().is_symlink()) {
        return Err(ChecksumError::Symlink(PathBuf::from("silt.toml")));
    }
    let src_root = pkg_root.join("src");
    let mut entries: Vec<(String, String)> = Vec::new();
    match fs::symlink_metadata(&src_root) {
        Ok(meta) if meta.file_type().is_symlink() => {
            return Err(ChecksumError::Symlink(PathBuf::from("src")));
        }
        Ok(meta) if meta.is_dir() => {
            collect_silt_files(pkg_root, &src_root, &mut entries)?;
        }
        _ => {}
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut hasher = Sha256::new();
    for (relpath, hash) in &entries {
        hasher.update(relpath.as_bytes());
        hasher.update(b"\0");
        hasher.update(hash.as_bytes());
        hasher.update(b"\n");
    }
    Ok(format!("sha256:{:x}", hasher.finalize()))
}

// ── Internals ──────────────────────────────────────────────────────────

/// Lexically normalize a path: collapse `.` and `..` without touching
/// the filesystem (we don't `canonicalize` because deps are loaded
/// before we know they exist, and we want stable absolute paths even
/// for missing deps so the error message matches the path the user
/// would expect on disk).
///
/// This is the single definition of lexical path normalization in the
/// tree. `pub` (not `pub(crate)`) because the CLI lives in the bin
/// crate: `silt add` (src/cli/add.rs) delegates here so the path form
/// it records in `silt.toml` (and prints on success) is normalized by
/// exactly the same rules lockfile resolution applies when it later
/// resolves that dep path. Audit round 101 LATENT: this body used to
/// be mirrored in src/cli/paths.rs; keep it unmirrored — a lock test
/// (tests/meta/round101_normalize_path_dedup_tests.rs) asserts the
/// `Component::ParentDir` pop-or-push loop appears exactly once under
/// src/.
pub fn normalize_path(p: &Path) -> PathBuf {
    let mut out = PathBuf::new();
    for comp in p.components() {
        use std::path::Component;
        match comp {
            Component::CurDir => {}
            Component::ParentDir => {
                if !out.pop() {
                    // Preserve leading `..` segments rather than
                    // silently dropping them; this is the same
                    // behavior `Path::join` would have taken.
                    out.push("..");
                }
            }
            other => out.push(other.as_os_str()),
        }
    }
    out
}

impl From<std::io::Error> for ChecksumError {
    fn from(e: std::io::Error) -> Self {
        ChecksumError::Io(e)
    }
}

/// Hash the `.silt` files under `dir` into `out`, keyed by their path
/// relative to `pkg_root`'s `src/`. Nothing is followed: the kind of an
/// entry is read from the entry itself, and a link is an error.
fn collect_silt_files(
    pkg_root: &Path,
    dir: &Path,
    out: &mut Vec<(String, String)>,
) -> Result<(), ChecksumError> {
    let base = pkg_root.join("src");
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let kind = entry.file_type()?;
        if kind.is_symlink() {
            return Err(ChecksumError::Symlink(
                path.strip_prefix(pkg_root).unwrap_or(&path).to_path_buf(),
            ));
        }
        if kind.is_dir() {
            collect_silt_files(pkg_root, &path, out)?;
        } else if path.extension().and_then(|s| s.to_str()) == Some("silt") {
            let bytes = fs::read(&path)?;
            let mut hasher = Sha256::new();
            hasher.update(&bytes);
            let file_hash = format!("{:x}", hasher.finalize());
            // Use forward slashes for stable hashing across platforms.
            // Otherwise checksums computed on Windows wouldn't match
            // those computed on Unix even for identical contents.
            let relpath = path
                .strip_prefix(&base)
                .unwrap_or(&path)
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            out.push((relpath, file_hash));
        }
    }
    Ok(())
}

// ── TOML rendering / parsing ───────────────────────────────────────────

const LOCKFILE_HEADER: &str = "# This file is generated by silt. Do not edit by hand.\n";

fn render_lockfile(lock: &Lockfile) -> String {
    let mut out = String::new();
    out.push_str(LOCKFILE_HEADER);
    out.push_str(&format!("version = {}\n", lock.version));
    let mut sorted: Vec<&LockedPackage> = lock.packages.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    for pkg in sorted {
        out.push('\n');
        out.push_str("[[package]]\n");
        out.push_str(&format!("name = {}\n", toml_escape_str(&pkg.name)));
        out.push_str(&format!("version = {}\n", toml_escape_str(&pkg.version)));
        match &pkg.source {
            LockedSource::Local => {
                // Root entry — no source / no checksum. Skipping these
                // fields is what marks the entry as "the local package".
            }
            LockedSource::Path { path } => {
                out.push_str(&format!(
                    "source = {{ path = {} }}\n",
                    toml_escape_str(&path.display().to_string())
                ));
                out.push_str(&format!("checksum = {}\n", toml_escape_str(&pkg.checksum)));
            }
            LockedSource::Git {
                url,
                ref_spec,
                resolved_sha,
            } => {
                // Schema rules for branch/tag/rev:
                //   - Rev(x): one `rev = x` field (the user's input *is* the
                //     resolved SHA).
                //   - Branch(name): both `branch = name` (user intent) and
                //     `rev = <resolved_sha>` (reproducible pin).
                //   - Tag(name): same shape as Branch but with `tag` instead.
                let mut parts = String::new();
                parts.push_str(&format!("git = {}", toml_escape_str(url)));
                match ref_spec {
                    GitRef::Rev(_) => {
                        parts.push_str(&format!(", rev = {}", toml_escape_str(resolved_sha)));
                    }
                    GitRef::Branch(name) => {
                        parts.push_str(&format!(", branch = {}", toml_escape_str(name)));
                        parts.push_str(&format!(", rev = {}", toml_escape_str(resolved_sha)));
                    }
                    GitRef::Tag(name) => {
                        parts.push_str(&format!(", tag = {}", toml_escape_str(name)));
                        parts.push_str(&format!(", rev = {}", toml_escape_str(resolved_sha)));
                    }
                }
                out.push_str(&format!("source = {{ {parts} }}\n"));
                out.push_str(&format!("checksum = {}\n", toml_escape_str(&pkg.checksum)));
            }
        }
    }
    out
}

/// `s` as a TOML basic string. Escaped is what TOML does not allow as
/// it is in a basic string: the quotation mark, the backslash, and the
/// control characters U+0000 to U+001F and U+007F (the tab, which TOML
/// would allow, included). Everything else is written as it is. A
/// string written here can be read back, whatever it holds; backslash
/// is the corner case that bites on Windows paths.
fn toml_escape_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 || c == '\u{7f}' => {
                out.push_str(&format!("\\u{:04X}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Why a text is not a lockfile: a message (the TOML parser's keeps its
/// own line breaks, see [`toml_error_message`]) and the byte range it is
/// about.
#[derive(Debug)]
struct LockParseError {
    message: String,
    span: (usize, usize),
}

fn parse_lockfile(text: &str) -> Result<Lockfile, LockParseError> {
    // We use the toml crate's untyped Value API rather than a typed
    // serde derive because the serde + toml combination requires
    // pulling in additional features. The schema is small enough that
    // the manual extraction below is easy to follow and emits sharper
    // error messages.
    let value: toml::Value = toml::from_str(text).map_err(|e: toml::de::Error| {
        // Only the parser's message is kept. Its own rendering of the
        // error quotes the offending line of the file.
        LockParseError {
            message: toml_error_message(e.message(), text),
            span: e.span().map_or((0, 0), |r| (r.start, r.end)),
        }
    })?;
    // The same text as a document, for the byte range of each entry.
    let doc = toml_edit::ImDocument::parse(text).ok();
    let entry_span = |index: usize| {
        doc.as_ref()
            .and_then(|doc| doc.get("package")?.as_array_of_tables()?.get(index)?.span())
            .map_or((0, 0), |r| (r.start, r.end))
    };
    // The byte range of `key` in the `source` of the entry `index`, or
    // of the entry when it has none.
    let source_value_span = |index: usize, key: &str| {
        doc.as_ref()
            .and_then(|doc| {
                doc.get("package")?
                    .as_array_of_tables()?
                    .get(index)?
                    .get("source")?
                    .as_inline_table()?
                    .get(key)?
                    .span()
            })
            .map_or_else(|| entry_span(index), |r| (r.start, r.end))
    };
    // A schema message quotes keys and values of the file, so it is
    // escaped whole: one line, whatever they hold.
    let whole = |message: String| LockParseError {
        message: git::escape_for_display(&message),
        span: (0, 0),
    };

    let table = value
        .as_table()
        .ok_or_else(|| whole("top-level must be a table".to_string()))?;

    let version = table
        .get("version")
        .and_then(|v| v.as_integer())
        .ok_or_else(|| whole("missing or invalid `version`".to_string()))?;
    if version != 1 {
        return Err(whole(format!(
            "unsupported lockfile version {version} (this binary supports version 1)"
        )));
    }

    let mut packages = Vec::new();
    if let Some(arr) = table.get("package") {
        let arr = arr
            .as_array()
            .ok_or_else(|| whole("`package` must be an array of tables".to_string()))?;
        for (index, entry) in arr.iter().enumerate() {
            let bad = |message: String| LockParseError {
                message: git::escape_for_display(&message),
                span: entry_span(index),
            };
            let entry = entry
                .as_table()
                .ok_or_else(|| bad("each [[package]] must be a table".to_string()))?;
            let name = entry
                .get("name")
                .and_then(|v| v.as_str())
                .ok_or_else(|| bad("[[package]] missing `name`".to_string()))?
                .to_string();
            let version_str = entry
                .get("version")
                .and_then(|v| v.as_str())
                .ok_or_else(|| bad(format!("[[package]] `{name}` missing `version`")))?
                .to_string();
            let checksum = || {
                entry
                    .get("checksum")
                    .and_then(|v| v.as_str())
                    .map(str::to_string)
                    .ok_or_else(|| bad(format!("[[package]] `{name}` has source but no checksum")))
            };
            let source = match entry.get("source") {
                None => LockedSource::Local,
                Some(src) => {
                    let src_table = src.as_table().ok_or_else(|| {
                        bad(format!("[[package]] `{name}` `source` must be a table"))
                    })?;
                    if let Some(p) = src_table.get("path").and_then(|v| v.as_str()) {
                        LockedSource::Path {
                            path: PathBuf::from(p),
                        }
                    } else if let Some(url) = src_table.get("git").and_then(|v| v.as_str()) {
                        // Required: `rev` (always the resolved commit).
                        // Optional: at most one of `branch` or `tag` to
                        // recover the user's original ref intent.
                        let resolved_sha = src_table
                            .get("rev")
                            .and_then(|v| v.as_str())
                            .ok_or_else(|| {
                                bad(format!(
                                    "[[package]] `{name}` git source missing `rev` (the resolved commit id)"
                                ))
                            })?
                            .to_string();
                        // `rev` names the cache directory the package is
                        // loaded from. A hand-edited value such as
                        // `../../../../x` would make silt load code from
                        // an arbitrary directory, and a prefix could name
                        // a tag, so only a full commit id is accepted.
                        if !git::is_full_commit_id(&resolved_sha) {
                            return Err(LockParseError {
                                span: source_value_span(index, "rev"),
                                ..bad(format!(
                                    "[[package]] `{name}` git source has invalid `rev` `{resolved_sha}`: \
                                 expected a full commit id of 40 or 64 hexadecimal characters"
                                ))
                            });
                        }
                        let branch = src_table.get("branch").and_then(|v| v.as_str());
                        let tag = src_table.get("tag").and_then(|v| v.as_str());
                        let ref_spec = match (branch, tag) {
                            (Some(_), Some(_)) => {
                                return Err(bad(format!(
                                    "[[package]] `{name}` git source has both `branch` and \
                                     `tag` (only one is allowed)"
                                )));
                            }
                            (Some(b), None) => GitRef::Branch(b.to_string()),
                            (None, Some(t)) => GitRef::Tag(t.to_string()),
                            (None, None) => GitRef::Rev(resolved_sha.clone()),
                        };
                        LockedSource::Git {
                            url: url.to_string(),
                            ref_spec,
                            resolved_sha,
                        }
                    } else {
                        return Err(bad(format!(
                            "[[package]] `{name}` source is unrecognized (expected `path` or `git`)"
                        )));
                    }
                }
            };
            let checksum = match source {
                LockedSource::Local => String::new(),
                _ => checksum()?,
            };
            packages.push(LockedPackage {
                name,
                version: version_str,
                source,
                checksum,
            });
        }
    }
    // Sort to match `write` so a load-then-write round-trips byte-stably.
    packages.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(Lockfile {
        version: 1,
        packages,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_round_trips() {
        let lock = Lockfile {
            version: 1,
            packages: vec![
                LockedPackage {
                    name: "calc".into(),
                    version: "0.1.0".into(),
                    source: LockedSource::Path {
                        path: PathBuf::from("/abs/path/to/calc"),
                    },
                    checksum: "sha256:deadbeef".into(),
                },
                LockedPackage {
                    name: "my_app".into(),
                    version: "0.1.0".into(),
                    source: LockedSource::Local,
                    checksum: String::new(),
                },
            ],
        };
        let text = render_lockfile(&lock);
        assert!(text.starts_with(LOCKFILE_HEADER));
        assert!(text.contains("[[package]]"));
        let parsed = parse_lockfile(&text).unwrap();
        assert_eq!(parsed, lock);
    }

    #[test]
    fn render_is_sorted_by_name() {
        let lock = Lockfile {
            version: 1,
            packages: vec![
                LockedPackage {
                    name: "z_pkg".into(),
                    version: "0.1.0".into(),
                    source: LockedSource::Path {
                        path: PathBuf::from("/z"),
                    },
                    checksum: "sha256:z".into(),
                },
                LockedPackage {
                    name: "a_pkg".into(),
                    version: "0.1.0".into(),
                    source: LockedSource::Local,
                    checksum: String::new(),
                },
            ],
        };
        let text = render_lockfile(&lock);
        let a_pos = text.find("a_pkg").expect("a_pkg present");
        let z_pos = text.find("z_pkg").expect("z_pkg present");
        assert!(a_pos < z_pos, "expected a_pkg before z_pkg in:\n{text}");
    }

    #[test]
    fn rejects_unknown_version() {
        let bad = "version = 999\n";
        let err = parse_lockfile(bad).unwrap_err();
        assert!(
            err.message.contains("unsupported lockfile version"),
            "{err:?}"
        );
    }

    /// A lockfile with one git package whose `rev` is `rev`.
    fn lockfile_with_git_rev(rev: &str) -> String {
        format!(
            "version = 1\n\n[[package]]\nname = \"remote\"\nversion = \"0.1.0\"\n\
             source = {{ git = \"https://example.com/r.git\", branch = \"main\", \
             rev = \"{rev}\" }}\n\
             checksum = \"sha256:deadbeef\"\n"
        )
    }

    #[test]
    fn rejects_git_rev_that_is_not_a_full_commit_id() {
        // `rev` names the cache directory a package is loaded from, so
        // a path-shaped value must never survive parsing, and a prefix
        // (which could name a tag) is not a pin.
        for rev in [
            "../../../../x",
            "abc1234/../x",
            "-abc1234",
            "main",
            "",
            "abc1234",
        ] {
            let text = lockfile_with_git_rev(rev);
            match parse_lockfile(&text) {
                Err(LockParseError { message, span }) => {
                    assert!(
                        message.contains("`remote`") && message.contains("invalid `rev`"),
                        "unexpected message for rev {rev:?}: {message}"
                    );
                    // The value of `rev`.
                    assert_eq!(&text[span.0..span.1], format!("\"{rev}\""), "{span:?}");
                }
                other => panic!("rev {rev:?} must be a parse error, got {other:?}"),
            }
        }
    }

    const HOSTILE_ESCAPED: &str = "x\\nerror: FORGED\\u{1b}[2K\\u{202e}";

    /// The diagnostic of loading `text` as a lockfile.
    fn load_error(tag: &str, text: &str) -> Diagnostic {
        let dir = std::env::temp_dir().join(format!("silt_lock_unit_{tag}_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let path = dir.join("silt.lock");
        fs::write(&path, text).unwrap();
        let mut sources = SourceMap::new();
        let d = Lockfile::load(&path, &mut sources).expect_err("the lockfile must be rejected");
        let _ = fs::remove_dir_all(&dir);
        d
    }

    #[test]
    fn load_error_is_a_printable_diagnostic() {
        let d = load_error(
            "name",
            "version = 1\n\n[[package]]\nname = \"x\\nerror: FORGED\\u001b[2K\\u202e\"\n",
        );
        assert_eq!(d.code, Code::LockfileInvalid);
        assert!(d.message.contains(HOSTILE_ESCAPED), "{d:?}");
        for line in std::iter::once(&d.message).chain(&d.notes) {
            assert!(!line.chars().any(git::needs_escape), "{line:?}");
        }
    }

    #[test]
    fn toml_parse_error_has_a_position_and_the_lines_of_the_parser() {
        // The offending line holds an escape character and U+202E; the
        // parser's own rendering would quote it. The file holds no
        // escape sequence, so the parser's lines are kept.
        let text = "version = 1\n\n[[package]]\nname = oops\u{1b}[2K\u{202e} error: FORGED\n";
        let err = parse_lockfile(text).unwrap_err();
        assert!(err.message.lines().count() >= 2, "{err:?}");
        assert!(!err.message.contains("FORGED"), "{err:?}");
        // On the fourth line, at `oops`.
        assert_eq!(&text[err.span.0..err.span.0 + 4], "oops", "{err:?}");

        // A key is quoted in the parser's message, and the key holds a
        // line break: one line.
        let text = "version = 1\n\"x\\nerror: FORGED\\u001b[2K\\u202e\" = 1\n\
                    \"x\\nerror: FORGED\\u001b[2K\\u202e\" = 2\n";
        let d = load_error("dupkey", text);
        assert!(d.notes.is_empty(), "{d:?}");
        assert!(
            d.message.contains(HOSTILE_ESCAPED) && !d.message.chars().any(git::needs_escape),
            "{d:?}"
        );
    }

    #[test]
    fn toml_escape_str_writes_what_the_parser_reads_back() {
        let mut every_control: String = ('\0'..='\u{1f}').collect();
        every_control.push('\u{7f}');
        for s in [
            every_control.as_str(),
            "1.0.0+a\u{7f}b",
            "quote \" backslash \\ C:\\Users\\me",
            "caf\u{e9} \u{2013} \u{65e5}\u{672c} \u{85}\u{a0}\u{202e}\u{2028}",
            "",
        ] {
            let written = toml_escape_str(s);
            assert!(
                !written.chars().any(|c| c.is_ascii_control()),
                "{s:?} was written with a control character: {written:?}"
            );
            let text = format!("v = {written}\n");
            let value: toml::Value = toml::from_str(&text).unwrap_or_else(|e| {
                panic!("{s:?} was written as {text:?}, which is not TOML: {e}")
            });
            let read = value
                .as_table()
                .and_then(|table| table.get("v"))
                .and_then(|v| v.as_str());
            assert_eq!(read, Some(s), "{text:?}");
        }
    }

    #[test]
    fn accepts_git_rev_of_either_hash_width() {
        for rev in ["a".repeat(40), "b".repeat(64)] {
            let text = lockfile_with_git_rev(&rev);
            let lock = parse_lockfile(&text).expect("valid rev parses");
            assert_eq!(
                lock.packages[0].source,
                LockedSource::Git {
                    url: "https://example.com/r.git".into(),
                    ref_spec: GitRef::Branch("main".into()),
                    resolved_sha: rev,
                }
            );
        }
    }

    #[cfg(unix)]
    #[test]
    fn checksum_rejects_a_symlink_in_the_sources() {
        let dir = std::env::temp_dir().join(format!("silt_lockfile_link_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(dir.join("pkg/src/inner")).unwrap();
        fs::write(dir.join("outside.silt"), b"pub fn f() { 1 }\n").unwrap();
        std::os::unix::fs::symlink(dir.join("outside.silt"), dir.join("pkg/src/inner/lib.silt"))
            .unwrap();
        match checksum_path_source(&dir.join("pkg")) {
            Err(ChecksumError::Symlink(path)) => {
                assert_eq!(path, Path::new("src/inner/lib.silt"));
            }
            other => panic!("a link in src/ must be rejected, got {other:?}"),
        }
        // `src` itself a link.
        fs::create_dir_all(dir.join("pkg2")).unwrap();
        std::os::unix::fs::symlink(dir.join("pkg/src"), dir.join("pkg2/src")).unwrap();
        assert!(matches!(
            checksum_path_source(&dir.join("pkg2")),
            Err(ChecksumError::Symlink(_))
        ));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn checksum_excludes_non_silt() {
        // Two trees with the same .silt content but different cruft
        // should produce the same checksum — the cruft must not flow
        // into the hash.
        let dir = std::env::temp_dir().join(format!("silt_lockfile_chk_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(dir.join("a/src")).unwrap();
        fs::create_dir_all(dir.join("b/src")).unwrap();
        fs::write(dir.join("a/src/lib.silt"), b"pub fn f() { 1 }\n").unwrap();
        fs::write(dir.join("b/src/lib.silt"), b"pub fn f() { 1 }\n").unwrap();
        // Cruft: lockfile and a non-silt file in src/ should not affect
        // the checksum.
        fs::write(dir.join("b/silt.lock"), b"# stale lockfile\n").unwrap();
        fs::write(dir.join("b/src/notes.txt"), b"not silt\n").unwrap();
        let h_a = checksum_path_source(&dir.join("a")).unwrap();
        let h_b = checksum_path_source(&dir.join("b")).unwrap();
        assert_eq!(h_a, h_b, "checksums should match: {h_a} vs {h_b}");
        let _ = fs::remove_dir_all(&dir);
    }
}
