//! Lock file (`silt.lock`) generation, parsing, and dep-tree resolution.
//!
//! A silt lockfile pins each transitive dependency of the local package
//! to a specific source location and a content checksum. The file lives
//! next to `silt.toml` and is regenerated when the manifest changes
//! (auto-update) or on demand via `silt update`.
//!
//! Supported source forms (as of v0.8): `LockedSource::Path` for path
//! deps and `LockedSource::Git` for git deps (`{ url, ref_spec,
//! resolved_sha }`). Future phases will add `Registry { name, version }`
//! without requiring a schema-version bump (consumers default to
//! "unknown source" and bail out if they don't recognise the variant —
//! see the TOML write/parse path below).
//!
//! # Layout
//!
//! ```toml
//! # This file is generated by silt. Do not edit by hand.
//! version = 1
//!
//! [[package]]
//! name = "my_app"
//! version = "0.1.0"
//!
//! [[package]]
//! name = "calc"
//! version = "0.1.0"
//! source = { path = "/abs/path/to/calc" }
//! checksum = "sha256:..."
//!
//! [[package]]
//! name = "remote"
//! version = "0.1.0"
//! source = { git = "https://example.com/r.git", branch = "main", rev = "<40-hex>" }
//! checksum = "sha256:..."
//! ```
//!
//! The local package gets an entry with no `source` or `checksum` (it
//! is the root of the dep graph; nothing pins *it*). All other entries
//! must carry both fields.
//!
//! # Why not `toml::to_string`?
//!
//! We render the lockfile manually rather than reaching for a TOML
//! serializer. Two reasons:
//!   - The current `toml` crate dep is configured `default-features =
//!     false, features = ["parse"]` — adding `display` would pull in
//!     extra serialization machinery we don't otherwise need.
//!   - Stable, deterministic output (sorted by name, fixed key order,
//!     literal "do not edit" header) is easier to produce by hand than
//!     to coax out of a generic serializer. The format is small enough
//!     (≤6 fields per package) that the manual writer is trivial.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;
use std::fs;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

use crate::git::{self, GitError, GitRef};
use crate::intern::{self, Symbol};
use crate::manifest::{Dependency, Manifest, ManifestError};

// ── Public types ───────────────────────────────────────────────────────

/// Top-level lockfile contents.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Lockfile {
    /// Schema version. Currently always `1`. Bumped on incompatible
    /// changes; the parser refuses unknown versions so old binaries
    /// don't silently misread a newer file.
    pub version: u32,
    /// All packages in the dep graph, including the local (root)
    /// package. Sorted by name for stable output.
    pub packages: Vec<LockedPackage>,
}

/// One pinned package entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockedPackage {
    /// Package name as written in its own `silt.toml` `[package].name`.
    pub name: String,
    /// Package version (semver string, validated by manifest loader).
    pub version: String,
    /// Where the package was resolved from. `Local` for the root —
    /// nothing pins the local package, so it has no source/checksum.
    pub source: LockedSource,
    /// Content hash of the dep's source tree (`"sha256:<hex>"`),
    /// computed by [`checksum_path_source`]. Empty for the root.
    pub checksum: String,
}

/// Where a locked package lives. The root entry uses `Local`; transitive
/// deps use `Path` or `Git`. `Registry` will land in a later phase.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LockedSource {
    /// Marker for the local (root) package — no `source` or `checksum`
    /// in the on-disk file.
    Local,
    /// Path-style dependency. `path` is always absolute so the lockfile
    /// is portable across cwd changes (you still pay the price of moving
    /// the workspace, of course; that's a known limitation of path deps).
    Path { path: PathBuf },
    /// Git-style dependency. `url` and the user's chosen `ref_spec` are
    /// preserved so `silt update` can re-resolve branch/tag deps;
    /// `resolved_sha` is the concrete commit pinned at lock time.
    Git {
        url: String,
        ref_spec: GitRef,
        resolved_sha: String,
    },
    // Future: Registry { name, version }.
}

// ── Errors ─────────────────────────────────────────────────────────────

/// Errors produced while resolving, reading, or writing a lockfile.
#[derive(Debug)]
pub enum LockfileError {
    /// I/O failure reading or writing the file.
    Io(std::io::Error, PathBuf),
    /// TOML syntax error or schema mismatch.
    Parse { message: String, path: PathBuf },
    /// A `path = "..."` dep points at a directory that doesn't exist.
    DepNotFound { name: String, path: PathBuf },
    /// A `path = "..."` dep exists but the directory has no `silt.toml`,
    /// so it isn't a silt package.
    DepNotPackage { name: String, path: PathBuf },
    /// The transitive manifest at one of the dep paths failed to load
    /// or validate. Carries the underlying [`ManifestError`].
    ManifestError(ManifestError),
    /// A git operation (ref resolution or fetch-to-cache) failed while
    /// resolving a git dependency. Carries the URL + the user's chosen
    /// ref form so the diagnostic can point at the specific entry, and
    /// the underlying [`GitError`] for the transport-level details.
    GitOperation {
        url: String,
        ref_spec: GitRef,
        source: GitError,
    },
}

impl fmt::Display for LockfileError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            LockfileError::Io(err, path) => {
                write!(f, "lockfile I/O error at {}: {}", path.display(), err)
            }
            LockfileError::Parse { message, path } => {
                write!(f, "invalid lockfile {}: {}", path.display(), message)
            }
            LockfileError::DepNotFound { name, path } => write!(
                f,
                "dependency `{name}` path does not exist: {}",
                path.display()
            ),
            LockfileError::DepNotPackage { name, path } => write!(
                f,
                "dependency `{name}` at {} is not a silt package (no silt.toml found)",
                path.display()
            ),
            LockfileError::ManifestError(err) => write!(f, "{err}"),
            LockfileError::GitOperation {
                url,
                ref_spec,
                source,
            } => write!(
                f,
                "git dependency `{url}` ({} = `{}`): {source}",
                ref_spec.kind(),
                ref_spec.as_ref_string()
            ),
        }
    }
}

impl std::error::Error for LockfileError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            LockfileError::Io(err, _) => Some(err),
            LockfileError::ManifestError(err) => Some(err),
            LockfileError::GitOperation { source, .. } => Some(source),
            _ => None,
        }
    }
}

impl From<ManifestError> for LockfileError {
    fn from(err: ManifestError) -> Self {
        LockfileError::ManifestError(err)
    }
}

// ── Resolution ─────────────────────────────────────────────────────────

impl Lockfile {
    /// Resolve a manifest's dependency tree into a [`Lockfile`].
    ///
    /// Walks the dep graph transitively: if dep A depends on dep B, B
    /// is also locked. Cycles in the dep graph are tolerated — the
    /// walker dedupes by absolute path, so `A -> B -> A` visits A
    /// twice but only locks it once. (The compiler's existing module
    /// cycle detection handles the runtime side; lockfile resolution
    /// just needs to terminate.)
    pub fn resolve(manifest: &Manifest) -> Result<Lockfile, LockfileError> {
        let mut packages: BTreeMap<String, LockedPackage> = BTreeMap::new();
        // Visited is keyed by the absolute path of the package root so
        // a diamond dep graph (X -> A -> Z, X -> B -> Z) only locks Z
        // once and a cycle (A -> B -> A) terminates cleanly. Git deps
        // map to their per-(url, sha) cache directory which uniquely
        // encodes the source — same git source = same cache path =
        // single visited entry, so dedup-by-path keeps working without
        // a separate (url, sha) key.
        let mut visited: BTreeSet<PathBuf> = BTreeSet::new();

        // Root entry: no source / no checksum (it's not pinned by
        // anything else; it pins everything else).
        let root_dir = manifest_dir(manifest).to_path_buf();
        visited.insert(root_dir.clone());
        let root_name = intern::resolve(manifest.package.name).to_string();
        packages.insert(
            root_name.clone(),
            LockedPackage {
                name: root_name,
                version: manifest.package.version.clone(),
                source: LockedSource::Local,
                checksum: String::new(),
            },
        );

        // BFS over the manifest's direct deps, then their deps, etc.
        // We read each transitive manifest fresh — the lockfile must
        // reflect the on-disk state of every package in the graph.
        // Each queue entry carries both the resolved root path (for
        // recursion + dedup) and the constructed `LockedSource` (so the
        // git arm can preserve the user's ref intent + the resolved SHA
        // without re-resolving when we materialise the LockedPackage).
        let mut queue: Vec<ResolvedDep> = Vec::new();
        for (name, dep) in &manifest.dependencies {
            let dep_name = intern::resolve(*name);
            queue.push(resolve_dep_path(&dep_name, dep, &root_dir)?);
        }

        while let Some(resolved) = queue.pop() {
            let dep_root = resolved.root_path.clone();
            if !visited.insert(dep_root.clone()) {
                continue;
            }
            let dep_manifest_path = dep_root.join("silt.toml");
            // The manifest must exist *and* be a valid package; both
            // failures are reported with paths so the user can find
            // the offending dep.
            if !dep_root.exists() {
                return Err(LockfileError::DepNotFound {
                    name: dep_root
                        .file_name()
                        .map(|n| n.to_string_lossy().into_owned())
                        .unwrap_or_else(|| dep_root.display().to_string()),
                    path: dep_root,
                });
            }
            if !dep_manifest_path.is_file() {
                return Err(LockfileError::DepNotPackage {
                    name: dep_root
                        .file_name()
                        .map(|n| n.to_string_lossy().into_owned())
                        .unwrap_or_else(|| dep_root.display().to_string()),
                    path: dep_root,
                });
            }
            let dep_manifest = Manifest::load(&dep_manifest_path)?;
            let checksum = checksum_path_source(&dep_root)
                .map_err(|e| LockfileError::Io(e, dep_root.clone()))?;
            let pkg_name = intern::resolve(dep_manifest.package.name).to_string();
            packages.entry(pkg_name.clone()).or_insert(LockedPackage {
                name: pkg_name,
                version: dep_manifest.package.version.clone(),
                source: resolved.source,
                checksum,
            });
            for (sub_name, sub_dep) in &dep_manifest.dependencies {
                let sub = resolve_dep_path(&intern::resolve(*sub_name), sub_dep, &dep_root)?;
                if !visited.contains(&sub.root_path) {
                    queue.push(sub);
                }
            }
        }

        Ok(Lockfile {
            version: 1,
            packages: packages.into_values().collect(),
        })
    }

    /// Load and validate a lockfile from disk.
    pub fn load(path: &Path) -> Result<Lockfile, LockfileError> {
        let text =
            fs::read_to_string(path).map_err(|e| LockfileError::Io(e, path.to_path_buf()))?;
        parse_lockfile(&text, path)
    }

    /// Write the lockfile to disk in stable TOML format.
    ///
    /// Output is deterministic: a fixed header, packages sorted by
    /// name, fixed key order within each entry. This makes lockfiles
    /// git-friendly — a no-op `silt update` produces a byte-identical
    /// file.
    pub fn write(&self, path: &Path) -> Result<(), LockfileError> {
        let rendered = render_lockfile(self);
        fs::write(path, rendered).map_err(|e| LockfileError::Io(e, path.to_path_buf()))
    }

    /// Returns true if this lockfile fully matches `manifest`.
    ///
    /// Matching means the lockfile's package set equals the closure of
    /// the manifest's transitive deps (plus the root). Used by the
    /// auto-regenerate logic in `silt run` / `check` / `test`: if
    /// `matches_manifest` is false the lockfile gets quietly rewritten
    /// before compilation proceeds.
    ///
    /// We deliberately only compare *names* here, not checksums or
    /// versions — content drift in a path dep is what `silt update`
    /// is for; the auto-update path is just for "I added a new dep,
    /// run silt run, it should Just Work".
    ///
    /// Cargo-style git semantics: this comparison does NOT contact the
    /// network to see if a branch dep's HEAD has advanced upstream. A
    /// lockfile pinning `branch = "main"` to SHA `abc...` stays valid
    /// across `silt run` invocations even when `main` has new commits;
    /// `silt update` is the explicit refresh trigger. The offline path
    /// implemented in [`Lockfile::resolve_offline`] is authoritative —
    /// it reuses the SHAs already pinned in `self` for every git dep
    /// rather than calling `git ls-remote`.
    pub fn matches_manifest(&self, manifest: &Manifest) -> bool {
        // Re-resolve the manifest to a fresh transitive set using the
        // offline variant (reusing stored SHAs for git deps). Any failure
        // means the lockfile is out of date (e.g. a new git dep without
        // a matching lock entry, or a missing path dep); the explicit
        // regenerate path then produces the real diagnostic.
        let Ok(fresh) = Lockfile::resolve_offline(manifest, self) else {
            return false;
        };
        let mut a: Vec<&str> = self.packages.iter().map(|p| p.name.as_str()).collect();
        let mut b: Vec<&str> = fresh.packages.iter().map(|p| p.name.as_str()).collect();
        a.sort();
        b.sort();
        a == b
    }

    /// Offline variant of [`Lockfile::resolve`]: uses the stored
    /// `resolved_sha` from `existing` for every git dep rather than
    /// calling `git ls-remote`. Used by [`Lockfile::matches_manifest`]
    /// to do the name-set comparison without network I/O.
    ///
    /// Returns `Err` if a git dep is present in `manifest` (directly or
    /// transitively) but has no matching entry (by `url` + `ref_spec`)
    /// in `existing` — this means the manifest has a new git dep and
    /// the caller should regenerate the lockfile via the full
    /// [`Lockfile::resolve`] path.
    ///
    /// Mirrors the BFS in `resolve` exactly, substituting
    /// `resolve_dep_path_offline` for the network-bound `resolve_dep_path`.
    fn resolve_offline(manifest: &Manifest, existing: &Lockfile) -> Result<Lockfile, LockfileError> {
        let mut packages: BTreeMap<String, LockedPackage> = BTreeMap::new();
        let mut visited: BTreeSet<PathBuf> = BTreeSet::new();

        let root_dir = manifest_dir(manifest).to_path_buf();
        visited.insert(root_dir.clone());
        let root_name = intern::resolve(manifest.package.name).to_string();
        packages.insert(
            root_name.clone(),
            LockedPackage {
                name: root_name,
                version: manifest.package.version.clone(),
                source: LockedSource::Local,
                checksum: String::new(),
            },
        );

        let mut queue: Vec<ResolvedDep> = Vec::new();
        for (name, dep) in &manifest.dependencies {
            let dep_name = intern::resolve(*name);
            queue.push(resolve_dep_path_offline(&dep_name, dep, &root_dir, existing)?);
        }

        while let Some(resolved) = queue.pop() {
            let dep_root = resolved.root_path.clone();
            if !visited.insert(dep_root.clone()) {
                continue;
            }
            let dep_manifest_path = dep_root.join("silt.toml");
            if !dep_root.exists() {
                return Err(LockfileError::DepNotFound {
                    name: dep_root
                        .file_name()
                        .map(|n| n.to_string_lossy().into_owned())
                        .unwrap_or_else(|| dep_root.display().to_string()),
                    path: dep_root,
                });
            }
            if !dep_manifest_path.is_file() {
                return Err(LockfileError::DepNotPackage {
                    name: dep_root
                        .file_name()
                        .map(|n| n.to_string_lossy().into_owned())
                        .unwrap_or_else(|| dep_root.display().to_string()),
                    path: dep_root,
                });
            }
            let dep_manifest = Manifest::load(&dep_manifest_path)?;
            let checksum = checksum_path_source(&dep_root)
                .map_err(|e| LockfileError::Io(e, dep_root.clone()))?;
            let pkg_name = intern::resolve(dep_manifest.package.name).to_string();
            packages.entry(pkg_name.clone()).or_insert(LockedPackage {
                name: pkg_name,
                version: dep_manifest.package.version.clone(),
                source: resolved.source,
                checksum,
            });
            for (sub_name, sub_dep) in &dep_manifest.dependencies {
                let sub = resolve_dep_path_offline(
                    &intern::resolve(*sub_name),
                    sub_dep,
                    &dep_root,
                    existing,
                )?;
                if !visited.contains(&sub.root_path) {
                    queue.push(sub);
                }
            }
        }

        Ok(Lockfile {
            version: 1,
            packages: packages.into_values().collect(),
        })
    }

    /// Build the `package_roots` map the compiler consumes from this
    /// lockfile + the local manifest.
    ///
    /// Layout convention (per the v0.7 plan): each package's importable
    /// source lives under `<pkg_root>/src/`. The local package's name
    /// comes from `manifest`; transitive deps' names come from their
    /// own lockfile entries.
    ///
    /// PR 5 (`silt add`) doesn't need to touch this — adding a dep to
    /// the manifest invalidates `matches_manifest`, the next compile
    /// regenerates the lock, and the new entry shows up here on the
    /// next call.
    pub fn package_roots(&self, manifest: &Manifest) -> std::collections::HashMap<Symbol, PathBuf> {
        let mut roots = std::collections::HashMap::new();
        let local_name = intern::resolve(manifest.package.name).to_string();
        // Local package: derive src/ from the manifest's directory so
        // we don't trust the lockfile to know the local checkout's
        // location (the lockfile carries no Local-source path).
        roots.insert(manifest.package.name, manifest_dir(manifest).join("src"));
        for pkg in &self.packages {
            if pkg.name == local_name {
                continue;
            }
            match &pkg.source {
                LockedSource::Path { path } => {
                    roots.insert(intern::intern(&pkg.name), path.join("src"));
                }
                LockedSource::Git {
                    url, resolved_sha, ..
                } => {
                    // The cache layout (`<silt-cache>/<url-hash>/<sha>/`)
                    // is computed deterministically from (url, sha), so
                    // we can resolve the import root without rereading
                    // the lockfile or hitting the network. The cache
                    // directory must already exist — `Lockfile::resolve`
                    // populates it before writing the lockfile.
                    if let Ok(cache_path) = git::cache_for(url, resolved_sha) {
                        roots.insert(intern::intern(&pkg.name), cache_path.join("src"));
                    }
                }
                LockedSource::Local => {}
            }
        }
        roots
    }
}

/// Compute a content-hash over a path-dep's source tree.
///
/// Walks `<pkg_root>/src/` recursively, hashes every `.silt` file's
/// contents, then folds those into a single SHA-256 keyed by relative
/// path. The encoding (`"{relpath}\0{filehash}\n"`) is unambiguous even
/// across paths containing newlines or NUL — neither is legal in silt
/// module names but the encoding stays robust regardless.
///
/// Excluded by virtue of not walking them: `silt.lock`, `target/`,
/// `.git/`. Sticking to `src/` makes the checksum mean exactly "the
/// sources the compiler will see".
pub fn checksum_path_source(pkg_root: &Path) -> Result<String, std::io::Error> {
    let src_root = pkg_root.join("src");
    let mut entries: Vec<(String, String)> = Vec::new();
    if src_root.is_dir() {
        collect_silt_files(&src_root, &src_root, &mut entries)?;
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut hasher = Sha256::new();
    for (relpath, hash) in &entries {
        hasher.update(relpath.as_bytes());
        hasher.update(b"\0");
        hasher.update(hash.as_bytes());
        hasher.update(b"\n");
    }
    Ok(format!("sha256:{:x}", hasher.finalize()))
}

// ── Internals ──────────────────────────────────────────────────────────

/// One step of dep-graph resolution: the on-disk root the consumer's
/// `Lockfile::resolve` BFS should walk into, plus the [`LockedSource`]
/// that should land in the corresponding [`LockedPackage`].
///
/// Bundling these together lets the git arm pass the resolved SHA up
/// to the BFS without re-running `git::resolve_ref`. For path deps
/// the source is just `Path { path }`; for git deps it carries the
/// user's ref intent and the network-resolved SHA.
struct ResolvedDep {
    root_path: PathBuf,
    source: LockedSource,
}

/// Resolve a [`Dependency`] entry to the on-disk root the BFS should
/// walk into, plus the [`LockedSource`] for the resulting lockfile entry.
///
/// Path deps lexically normalize relative to the consumer's manifest
/// directory. Git deps run `git ls-remote` to convert branch/tag refs
/// to a concrete SHA, then `git clone` (atomic via `<dir>.tmp` rename)
/// into the per-(url, sha) cache directory and return that path.
///
/// The `name` is used only for future diagnostics — currently the
/// caller materializes any `DepNotFound` / `DepNotPackage` errors with
/// the directory name; git errors are tagged with their URL + ref.
fn resolve_dep_path(
    _name: &str,
    dep: &Dependency,
    parent_dir: &Path,
) -> Result<ResolvedDep, LockfileError> {
    match dep {
        Dependency::Path { path } => {
            let abs = normalize_path(&parent_dir.join(path));
            Ok(ResolvedDep {
                root_path: abs.clone(),
                source: LockedSource::Path { path: abs },
            })
        }
        Dependency::Git { url, ref_spec } => {
            // Resolve user-specified ref (Rev/Branch/Tag) to a concrete
            // commit SHA. For Rev this is offline; for Branch/Tag it
            // hits the remote via `git ls-remote`.
            let resolved_sha =
                git::resolve_ref(url, ref_spec).map_err(|e| LockfileError::GitOperation {
                    url: url.clone(),
                    ref_spec: ref_spec.clone(),
                    source: e,
                })?;
            // Materialise the cache directory. Idempotent — a populated
            // cache from a previous run is reused without re-cloning.
            let cache_path = git::fetch_to_cache(url, &resolved_sha).map_err(|e| {
                LockfileError::GitOperation {
                    url: url.clone(),
                    ref_spec: ref_spec.clone(),
                    source: e,
                }
            })?;
            Ok(ResolvedDep {
                root_path: cache_path,
                source: LockedSource::Git {
                    url: url.clone(),
                    ref_spec: ref_spec.clone(),
                    resolved_sha,
                },
            })
        }
    }
}

/// Offline variant of [`resolve_dep_path`]: for git deps, looks up the
/// matching `(url, ref_spec)` entry in `existing` and reuses its stored
/// `resolved_sha` rather than calling `git ls-remote`. For path deps,
/// behaves identically to `resolve_dep_path` (path deps are offline).
///
/// Returns a [`LockfileError::GitOperation`] wrapping [`GitError::RefNotFound`]
/// when a git dep in the manifest has no matching entry in `existing`
/// (by `url` and `ref_spec` equality) — the caller treats this as "lock
/// is stale, regenerate via the full network path".
///
/// Also fails if the cache directory for the resolved SHA is missing its
/// `silt.toml`: we cannot read the transitive manifest to recurse, so
/// the offline comparison is incomplete and we fall back to the full
/// regenerate. In practice `Lockfile::resolve` populates the cache on
/// the first lock-write, so on steady-state `silt run` invocations the
/// cache is always present.
fn resolve_dep_path_offline(
    _name: &str,
    dep: &Dependency,
    parent_dir: &Path,
    existing: &Lockfile,
) -> Result<ResolvedDep, LockfileError> {
    match dep {
        Dependency::Path { path } => {
            let abs = normalize_path(&parent_dir.join(path));
            Ok(ResolvedDep {
                root_path: abs.clone(),
                source: LockedSource::Path { path: abs },
            })
        }
        Dependency::Git { url, ref_spec } => {
            // Find the matching lockfile entry by (url, ref_spec).
            let matching = existing.packages.iter().find_map(|pkg| match &pkg.source {
                LockedSource::Git {
                    url: lu,
                    ref_spec: lr,
                    resolved_sha,
                } if lu == url && lr == ref_spec => Some(resolved_sha.clone()),
                _ => None,
            });
            let resolved_sha = matching.ok_or_else(|| LockfileError::GitOperation {
                url: url.clone(),
                ref_spec: ref_spec.clone(),
                source: GitError::RefNotFound {
                    url: url.clone(),
                    ref_spec: ref_spec.clone(),
                },
            })?;
            // Compute the cache path deterministically from (url, sha).
            // The cache must already be populated — if not, the offline
            // comparison cannot recurse into the git dep's manifest to
            // gather transitive deps, so we bail out (caller regenerates).
            let cache_path =
                git::cache_for(url, &resolved_sha).map_err(|e| LockfileError::GitOperation {
                    url: url.clone(),
                    ref_spec: ref_spec.clone(),
                    source: e,
                })?;
            Ok(ResolvedDep {
                root_path: cache_path,
                source: LockedSource::Git {
                    url: url.clone(),
                    ref_spec: ref_spec.clone(),
                    resolved_sha,
                },
            })
        }
    }
}

/// Lexically normalize a path: collapse `.` and `..` without touching
/// the filesystem (we don't `canonicalize` because deps are loaded
/// before we know they exist, and we want stable absolute paths even
/// for missing deps so the error message matches the path the user
/// would expect on disk).
fn normalize_path(p: &Path) -> PathBuf {
    let mut out = PathBuf::new();
    for comp in p.components() {
        use std::path::Component;
        match comp {
            Component::CurDir => {}
            Component::ParentDir => {
                if !out.pop() {
                    // Preserve leading `..` segments rather than
                    // silently dropping them; this is the same
                    // behavior `Path::join` would have taken.
                    out.push("..");
                }
            }
            other => out.push(other.as_os_str()),
        }
    }
    out
}

fn manifest_dir(manifest: &Manifest) -> &Path {
    manifest
        .manifest_path
        .parent()
        .expect("manifest path always has a parent")
}

fn collect_silt_files(
    base: &Path,
    dir: &Path,
    out: &mut Vec<(String, String)>,
) -> Result<(), std::io::Error> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_silt_files(base, &path, out)?;
        } else if path.extension().and_then(|s| s.to_str()) == Some("silt") {
            let bytes = fs::read(&path)?;
            let mut hasher = Sha256::new();
            hasher.update(&bytes);
            let file_hash = format!("{:x}", hasher.finalize());
            // Use forward slashes for stable hashing across platforms.
            // Otherwise checksums computed on Windows wouldn't match
            // those computed on Unix even for identical contents.
            let relpath = path
                .strip_prefix(base)
                .unwrap_or(&path)
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            out.push((relpath, file_hash));
        }
    }
    Ok(())
}

// ── TOML rendering / parsing ───────────────────────────────────────────

const LOCKFILE_HEADER: &str = "# This file is generated by silt. Do not edit by hand.\n";

fn render_lockfile(lock: &Lockfile) -> String {
    let mut out = String::new();
    out.push_str(LOCKFILE_HEADER);
    out.push_str(&format!("version = {}\n", lock.version));
    let mut sorted: Vec<&LockedPackage> = lock.packages.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    for pkg in sorted {
        out.push('\n');
        out.push_str("[[package]]\n");
        out.push_str(&format!("name = {}\n", toml_escape_str(&pkg.name)));
        out.push_str(&format!("version = {}\n", toml_escape_str(&pkg.version)));
        match &pkg.source {
            LockedSource::Local => {
                // Root entry — no source / no checksum. Skipping these
                // fields is what marks the entry as "the local package".
            }
            LockedSource::Path { path } => {
                out.push_str(&format!(
                    "source = {{ path = {} }}\n",
                    toml_escape_str(&path.display().to_string())
                ));
                out.push_str(&format!("checksum = {}\n", toml_escape_str(&pkg.checksum)));
            }
            LockedSource::Git {
                url,
                ref_spec,
                resolved_sha,
            } => {
                // Schema rules for branch/tag/rev:
                //   - Rev(x): one `rev = x` field (the user's input *is* the
                //     resolved SHA).
                //   - Branch(name): both `branch = name` (user intent) and
                //     `rev = <resolved_sha>` (reproducible pin).
                //   - Tag(name): same shape as Branch but with `tag` instead.
                let mut parts = String::new();
                parts.push_str(&format!("git = {}", toml_escape_str(url)));
                match ref_spec {
                    GitRef::Rev(_) => {
                        parts.push_str(&format!(", rev = {}", toml_escape_str(resolved_sha)));
                    }
                    GitRef::Branch(name) => {
                        parts.push_str(&format!(", branch = {}", toml_escape_str(name)));
                        parts.push_str(&format!(", rev = {}", toml_escape_str(resolved_sha)));
                    }
                    GitRef::Tag(name) => {
                        parts.push_str(&format!(", tag = {}", toml_escape_str(name)));
                        parts.push_str(&format!(", rev = {}", toml_escape_str(resolved_sha)));
                    }
                }
                out.push_str(&format!("source = {{ {parts} }}\n"));
                out.push_str(&format!("checksum = {}\n", toml_escape_str(&pkg.checksum)));
            }
        }
    }
    out
}

/// Minimal TOML basic-string escape — handles `"` and `\` only, which
/// is sufficient for the strings we emit (paths, names, versions,
/// hashes). Backslash is the corner case that bites on Windows paths.
fn toml_escape_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04X}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn parse_lockfile(text: &str, path: &Path) -> Result<Lockfile, LockfileError> {
    // We use the toml crate's untyped Value API rather than a typed
    // serde derive because the serde + toml combination requires
    // pulling in additional features. The schema is small enough that
    // the manual extraction below is easy to follow and emits sharper
    // error messages.
    let value: toml::Value = toml::from_str(text).map_err(|e| LockfileError::Parse {
        message: e.to_string(),
        path: path.to_path_buf(),
    })?;

    let table = value.as_table().ok_or_else(|| LockfileError::Parse {
        message: "top-level must be a table".to_string(),
        path: path.to_path_buf(),
    })?;

    let version = table
        .get("version")
        .and_then(|v| v.as_integer())
        .ok_or_else(|| LockfileError::Parse {
            message: "missing or invalid `version`".to_string(),
            path: path.to_path_buf(),
        })?;
    if version != 1 {
        return Err(LockfileError::Parse {
            message: format!(
                "unsupported lockfile version {version} (this binary supports version 1)"
            ),
            path: path.to_path_buf(),
        });
    }

    let mut packages = Vec::new();
    if let Some(arr) = table.get("package") {
        let arr = arr.as_array().ok_or_else(|| LockfileError::Parse {
            message: "`package` must be an array of tables".to_string(),
            path: path.to_path_buf(),
        })?;
        for entry in arr {
            let entry = entry.as_table().ok_or_else(|| LockfileError::Parse {
                message: "each [[package]] must be a table".to_string(),
                path: path.to_path_buf(),
            })?;
            let name = entry
                .get("name")
                .and_then(|v| v.as_str())
                .ok_or_else(|| LockfileError::Parse {
                    message: "[[package]] missing `name`".to_string(),
                    path: path.to_path_buf(),
                })?
                .to_string();
            let version_str = entry
                .get("version")
                .and_then(|v| v.as_str())
                .ok_or_else(|| LockfileError::Parse {
                    message: format!("[[package]] `{name}` missing `version`"),
                    path: path.to_path_buf(),
                })?
                .to_string();
            let (source, checksum) = match entry.get("source") {
                None => (LockedSource::Local, String::new()),
                Some(src) => {
                    let src_table = src.as_table().ok_or_else(|| LockfileError::Parse {
                        message: format!("[[package]] `{name}` `source` must be a table"),
                        path: path.to_path_buf(),
                    })?;
                    if let Some(p) = src_table.get("path").and_then(|v| v.as_str()) {
                        let checksum = entry
                            .get("checksum")
                            .and_then(|v| v.as_str())
                            .ok_or_else(|| LockfileError::Parse {
                                message: format!("[[package]] `{name}` has source but no checksum"),
                                path: path.to_path_buf(),
                            })?
                            .to_string();
                        (
                            LockedSource::Path {
                                path: PathBuf::from(p),
                            },
                            checksum,
                        )
                    } else if let Some(url) = src_table.get("git").and_then(|v| v.as_str()) {
                        // Required: `rev` (always the resolved SHA).
                        // Optional: at most one of `branch` or `tag` to
                        // recover the user's original ref intent.
                        let resolved_sha = src_table
                            .get("rev")
                            .and_then(|v| v.as_str())
                            .ok_or_else(|| LockfileError::Parse {
                                message: format!(
                                    "[[package]] `{name}` git source missing `rev` (the resolved SHA)"
                                ),
                                path: path.to_path_buf(),
                            })?
                            .to_string();
                        let branch = src_table.get("branch").and_then(|v| v.as_str());
                        let tag = src_table.get("tag").and_then(|v| v.as_str());
                        let ref_spec = match (branch, tag) {
                            (Some(_), Some(_)) => {
                                return Err(LockfileError::Parse {
                                    message: format!(
                                        "[[package]] `{name}` git source has both `branch` and \
                                         `tag` (only one is allowed)"
                                    ),
                                    path: path.to_path_buf(),
                                });
                            }
                            (Some(b), None) => GitRef::Branch(b.to_string()),
                            (None, Some(t)) => GitRef::Tag(t.to_string()),
                            (None, None) => GitRef::Rev(resolved_sha.clone()),
                        };
                        let checksum = entry
                            .get("checksum")
                            .and_then(|v| v.as_str())
                            .ok_or_else(|| LockfileError::Parse {
                                message: format!("[[package]] `{name}` has source but no checksum"),
                                path: path.to_path_buf(),
                            })?
                            .to_string();
                        (
                            LockedSource::Git {
                                url: url.to_string(),
                                ref_spec,
                                resolved_sha,
                            },
                            checksum,
                        )
                    } else {
                        return Err(LockfileError::Parse {
                            message: format!(
                                "[[package]] `{name}` source is unrecognized (expected `path` or `git`)"
                            ),
                            path: path.to_path_buf(),
                        });
                    }
                }
            };
            packages.push(LockedPackage {
                name,
                version: version_str,
                source,
                checksum,
            });
        }
    }
    // Sort to match `write` so a load-then-write round-trips byte-stably.
    packages.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(Lockfile {
        version: 1,
        packages,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_round_trips() {
        let lock = Lockfile {
            version: 1,
            packages: vec![
                LockedPackage {
                    name: "calc".into(),
                    version: "0.1.0".into(),
                    source: LockedSource::Path {
                        path: PathBuf::from("/abs/path/to/calc"),
                    },
                    checksum: "sha256:deadbeef".into(),
                },
                LockedPackage {
                    name: "my_app".into(),
                    version: "0.1.0".into(),
                    source: LockedSource::Local,
                    checksum: String::new(),
                },
            ],
        };
        let text = render_lockfile(&lock);
        assert!(text.starts_with(LOCKFILE_HEADER));
        assert!(text.contains("[[package]]"));
        let parsed = parse_lockfile(&text, Path::new("test.lock")).unwrap();
        assert_eq!(parsed, lock);
    }

    #[test]
    fn render_is_sorted_by_name() {
        let lock = Lockfile {
            version: 1,
            packages: vec![
                LockedPackage {
                    name: "z_pkg".into(),
                    version: "0.1.0".into(),
                    source: LockedSource::Path {
                        path: PathBuf::from("/z"),
                    },
                    checksum: "sha256:z".into(),
                },
                LockedPackage {
                    name: "a_pkg".into(),
                    version: "0.1.0".into(),
                    source: LockedSource::Local,
                    checksum: String::new(),
                },
            ],
        };
        let text = render_lockfile(&lock);
        let a_pos = text.find("a_pkg").expect("a_pkg present");
        let z_pos = text.find("z_pkg").expect("z_pkg present");
        assert!(a_pos < z_pos, "expected a_pkg before z_pkg in:\n{text}");
    }

    #[test]
    fn rejects_unknown_version() {
        let bad = "version = 999\n";
        let err = parse_lockfile(bad, Path::new("x.lock")).unwrap_err();
        assert!(matches!(err, LockfileError::Parse { .. }));
    }

    #[test]
    fn checksum_excludes_non_silt() {
        // Two trees with the same .silt content but different cruft
        // should produce the same checksum — the cruft must not flow
        // into the hash.
        let dir = std::env::temp_dir().join(format!("silt_lockfile_chk_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(dir.join("a/src")).unwrap();
        fs::create_dir_all(dir.join("b/src")).unwrap();
        fs::write(dir.join("a/src/lib.silt"), b"pub fn f() = 1\n").unwrap();
        fs::write(dir.join("b/src/lib.silt"), b"pub fn f() = 1\n").unwrap();
        // Cruft: lockfile and a non-silt file in src/ should not affect
        // the checksum.
        fs::write(dir.join("b/silt.lock"), b"# stale lockfile\n").unwrap();
        fs::write(dir.join("b/src/notes.txt"), b"not silt\n").unwrap();
        let h_a = checksum_path_source(&dir.join("a")).unwrap();
        let h_b = checksum_path_source(&dir.join("b")).unwrap();
        assert_eq!(h_a, h_b, "checksums should match: {h_a} vs {h_b}");
        let _ = fs::remove_dir_all(&dir);
    }
}
